// ============================================================
// KANA KATAKANA DATA - basic, dakuten, handakuten, yoon
// ============================================================

'use strict';

var KANA_MAP = typeof KANA_MAP !== 'undefined' ? KANA_MAP : {};

Object.assign(KANA_MAP, {
  // ─────────────────── 가타가나 기본 ───────────────────
  'ア': { romaji:'a',   korean:'아', english:'ah',    type:'katakana', tip:'알파벳 A처럼 생겼어요! A → ア → "아" 🔤',
    examples:[{word:'アイス',meaning:'아이스크림 (ice cream)'},{word:'アメリカ',meaning:'미국 (America)'},{word:'アニメ',meaning:'애니메이션 (anime)'}]},
  'イ': { romaji:'i',   korean:'이', english:'ee',    type:'katakana', tip:'알파벳 I처럼 곧게 서 있어요! I → イ → "이" 🔤',
    examples:[{word:'イタリア',meaning:'이탈리아 (Italy)'},{word:'インターネット',meaning:'인터넷 (internet)'}]},
  'ウ': { romaji:'u',   korean:'우', english:'oo',    type:'katakana', tip:'우산(umbrella) 위 부분처럼 생겼어요 → "우" ☂️',
    examples:[{word:'ウイルス',meaning:'바이러스 (virus)'},{word:'ウクレレ',meaning:'우쿨렐레 (ukulele)'}]},
  'エ': { romaji:'e',   korean:'에', english:'eh',    type:'katakana', tip:'공사장 H빔처럼 생겼어요 → エレベーター(엘리베이터) → "에" 🏗️',
    examples:[{word:'エアコン',meaning:'에어컨 (air conditioner)'},{word:'エレベーター',meaning:'엘리베이터 (elevator)'}]},
  'オ': { romaji:'o',   korean:'오', english:'oh',    type:'katakana', tip:'알파벳 T를 비틀어 놓은 듯 → "오" 💡',
    examples:[{word:'オレンジ',meaning:'오렌지 (orange)'},{word:'オーストラリア',meaning:'호주 (Australia)'}]},

  'カ': { romaji:'ka',  korean:'카', english:'kah',   type:'katakana', tip:'알파벳 K처럼 생겼어요! K → カ → "카" 🔤',
    examples:[{word:'カメラ',meaning:'카메라 (camera)'},{word:'カフェ',meaning:'카페 (cafe)'},{word:'カレー',meaning:'카레 (curry)'}]},
  'キ': { romaji:'ki',  korean:'키', english:'key',   type:'katakana', tip:'나무(木) 모양에 두 가지 → "키" 나무 🌳',
    examples:[{word:'キッチン',meaning:'부엌 (kitchen)'},{word:'キャンプ',meaning:'캠핑 (camping)'}]},
  'ク': { romaji:'ku',  korean:'쿠', english:'koo',   type:'katakana', tip:'새 부리가 왼쪽으로 → "쿠" 우는 새 🐦',
    examples:[{word:'クラス',meaning:'클래스 (class)'},{word:'クリスマス',meaning:'크리스마스 (Christmas)'}]},
  'ケ': { romaji:'ke',  korean:'케', english:'keh',   type:'katakana', tip:'알파벳 K처럼 각진 모양 → "케" 💡',
    examples:[{word:'ケーキ',meaning:'케이크 (cake)'},{word:'ケータイ',meaning:'휴대폰 (mobile phone)'}]},
  'コ': { romaji:'ko',  korean:'코', english:'koh',   type:'katakana', tip:'두 가로선이 직각으로 → "코" 코너 📐',
    examples:[{word:'コーヒー',meaning:'커피 (coffee)'},{word:'コンビニ',meaning:'편의점 (convenience store)'}]},

  'サ': { romaji:'sa',  korean:'사', english:'sah',   type:'katakana', tip:'세 획이 있어요 → "사" 삼(三)처럼 3️⃣',
    examples:[{word:'サラダ',meaning:'샐러드 (salad)'},{word:'サッカー',meaning:'축구 (soccer)'}]},
  'シ': { romaji:'shi', korean:'시', english:'shee',  type:'katakana', tip:'웃는 입 모양 :) → "시" 히히 😊',
    examples:[{word:'シャツ',meaning:'셔츠 (shirt)'},{word:'システム',meaning:'시스템 (system)'}]},
  'ス': { romaji:'su',  korean:'스', english:'soo',   type:'katakana', tip:'숟가락처럼 생겼어요 → "스" 숟가락 🥄',
    examples:[{word:'スポーツ',meaning:'스포츠 (sports)'},{word:'スマホ',meaning:'스마트폰 (smartphone)'}]},
  'セ': { romaji:'se',  korean:'세', english:'seh',   type:'katakana', tip:'"세"를 단순하게 → "세" 📝',
    examples:[{word:'セーター',meaning:'스웨터 (sweater)'},{word:'センター',meaning:'센터 (center)'}]},
  'ソ': { romaji:'so',  korean:'소', english:'soh',   type:'katakana', tip:'/ 와 비슷하지만 시작이 위 → "소" ↗️',
    examples:[{word:'ソファ',meaning:'소파 (sofa)'},{word:'ソフトウェア',meaning:'소프트웨어 (software)'}]},

  'タ': { romaji:'ta',  korean:'타', english:'tah',   type:'katakana', tip:'알파벳 タ → "타" 짧은 획이 특징 📌',
    examples:[{word:'タクシー',meaning:'택시 (taxi)'},{word:'テーブル',meaning:'테이블 (table)'}]},
  'チ': { romaji:'chi', korean:'치', english:'chee',  type:'katakana', tip:'치즈처럼 늘어지는 모양 → チーズ(치즈) → "치" 🧀',
    examples:[{word:'チーズ',meaning:'치즈 (cheese)'},{word:'チケット',meaning:'티켓 (ticket)'}]},
  'ツ': { romaji:'tsu', korean:'츠', english:'tsoo',  type:'katakana', tip:'웃는 눈 :) 가로로 누운 형태 → "츠" 웃음 😄',
    examples:[{word:'ツアー',meaning:'투어 (tour)'},{word:'ツイッター',meaning:'트위터 (Twitter)'}]},
  'テ': { romaji:'te',  korean:'테', english:'teh',   type:'katakana', tip:'십자가 모양 T → テレビ(TV) → "테" 📺',
    examples:[{word:'テレビ',meaning:'TV (television)'},{word:'テスト',meaning:'시험 (test)'}]},
  'ト': { romaji:'to',  korean:'토', english:'toh',   type:'katakana', tip:'토끼 귀처럼 위로 솟은 모양 → "토" 🐰',
    examples:[{word:'トマト',meaning:'토마토 (tomato)'},{word:'トイレ',meaning:'화장실 (toilet)'}]},

  'ナ': { romaji:'na',  korean:'나', english:'nah',   type:'katakana', tip:'칼 모양 → "나" 나이프 🔪',
    examples:[{word:'ナイフ',meaning:'나이프 (knife)'},{word:'ナンバー',meaning:'번호 (number)'}]},
  'ニ': { romaji:'ni',  korean:'니', english:'nee',   type:'katakana', tip:'두 가로선 = → "니" 이이 ═',
    examples:[{word:'ニュース',meaning:'뉴스 (news)'},{word:'ニコニコ',meaning:'니코니코 (smiling)'}]},
  'ヌ': { romaji:'nu',  korean:'누', english:'noo',   type:'katakana', tip:'숫자 7처럼 구부러짐 → "누" 7️⃣',
    examples:[{word:'ヌードル',meaning:'누들 (noodle)'},{word:'ヌード',meaning:'누드 (nude)'}]},
  'ネ': { romaji:'ne',  korean:'네', english:'neh',   type:'katakana', tip:'네트워크처럼 연결된 획들 → "네" 🔗',
    examples:[{word:'ネット',meaning:'인터넷/망 (net)'},{word:'ネクタイ',meaning:'넥타이 (necktie)'}]},
  'ノ': { romaji:'no',  korean:'노', english:'noh',   type:'katakana', tip:'비스듬한 획 하나 / → "노" 미끄럼틀 🛝',
    examples:[{word:'ノート',meaning:'노트 (notebook)'},{word:'ノック',meaning:'노크 (knock)'}]},

  'ハ': { romaji:'ha',  korean:'하', english:'hah',   type:'katakana', tip:'알파벳 H의 아래 절반 모양 → "하" H',
    examples:[{word:'ハンバーガー',meaning:'햄버거 (hamburger)'},{word:'ハワイ',meaning:'하와이 (Hawaii)'}]},
  'ヒ': { romaji:'hi',  korean:'히', english:'hee',   type:'katakana', tip:'F처럼 생겼어요 → "히" 짧은 획이 특징 📝',
    examples:[{word:'ヒーロー',meaning:'히어로 (hero)'},{word:'ヒント',meaning:'힌트 (hint)'}]},
  'フ': { romaji:'fu',  korean:'후', english:'foo',   type:'katakana', tip:'후크(hook) 모양 → "후" 갈고리 🪝',
    examples:[{word:'フランス',meaning:'프랑스 (France)'},{word:'フルーツ',meaning:'과일 (fruit)'}]},
  'ヘ': { romaji:'he',  korean:'헤', english:'heh',   type:'katakana', tip:'へ와 똑같이 생겼어요! 산봉우리 → "헤" 🏔️',
    examples:[{word:'ヘルメット',meaning:'헬멧 (helmet)'},{word:'ヘッドフォン',meaning:'헤드폰 (headphones)'}]},
  'ホ': { romaji:'ho',  korean:'호', english:'hoh',   type:'katakana', tip:'十자에 두 획 더 → "호" 호텔(ホテル) 🏨',
    examples:[{word:'ホテル',meaning:'호텔 (hotel)'},{word:'ホームページ',meaning:'홈페이지 (homepage)'}]},

  'マ': { romaji:'ma',  korean:'마', english:'mah',   type:'katakana', tip:'알파벳 M의 변형 → "마" 매우 비슷해요 M',
    examples:[{word:'マクドナルド',meaning:'맥도날드 (McDonald\'s)'},{word:'マスク',meaning:'마스크 (mask)'}]},
  'ミ': { romaji:'mi',  korean:'미', english:'mee',   type:'katakana', tip:'세 가로선 ≡ → "미" 미미 ≡',
    examples:[{word:'ミルク',meaning:'우유 (milk)'},{word:'ミュージック',meaning:'음악 (music)'}]},
  'ム': { romaji:'mu',  korean:'무', english:'moo',   type:'katakana', tip:'소(牛) 뿔처럼 → "무" 소 울음 🐄',
    examples:[{word:'ムード',meaning:'무드 (mood)'},{word:'ムービー',meaning:'영화 (movie)'}]},
  'メ': { romaji:'me',  korean:'메', english:'meh',   type:'katakana', tip:'×처럼 교차하는 획 → "메" 교차로 ✖️',
    examples:[{word:'メール',meaning:'이메일 (email)'},{word:'メニュー',meaning:'메뉴 (menu)'}]},
  'モ': { romaji:'mo',  korean:'모', english:'moh',   type:'katakana', tip:'모(毛)처럼 획이 내려감 → "모" 털 🌾',
    examples:[{word:'モデル',meaning:'모델 (model)'},{word:'モバイル',meaning:'모바일 (mobile)'}]},

  'ヤ': { romaji:'ya',  korean:'야', english:'yah',   type:'katakana', tip:'알파벳 Y처럼 생겼어요! Y → ヤ → "야" 🔤',
    examples:[{word:'ヤフー',meaning:'야후 (Yahoo)'},{word:'ヤード',meaning:'야드 (yard)'}]},
  'ユ': { romaji:'yu',  korean:'유', english:'yoo',   type:'katakana', tip:'알파벳 U처럼 구부러짐 → "유" U 🔤',
    examples:[{word:'ユーチューブ',meaning:'유튜브 (YouTube)'},{word:'ユニフォーム',meaning:'유니폼 (uniform)'}]},
  'ヨ': { romaji:'yo',  korean:'요', english:'yoh',   type:'katakana', tip:'알파벳 E를 비틀어 놓은 듯 → "요" E',
    examples:[{word:'ヨーグルト',meaning:'요거트 (yogurt)'},{word:'ヨーロッパ',meaning:'유럽 (Europe)'}]},

  'ラ': { romaji:'ra',  korean:'라', english:'rah',   type:'katakana', tip:'숫자 7처럼 생겼어요 → "라" 7️⃣',
    examples:[{word:'ラーメン',meaning:'라면 (ramen)'},{word:'ラジオ',meaning:'라디오 (radio)'}]},
  'リ': { romaji:'ri',  korean:'리', english:'ree',   type:'katakana', tip:'두 줄이 나란히 내려가요 → "리" リリ 🌿',
    examples:[{word:'リモコン',meaning:'리모컨 (remote control)'},{word:'リズム',meaning:'리듬 (rhythm)'}]},
  'ル': { romaji:'ru',  korean:'루', english:'roo',   type:'katakana', tip:'각진 ル 모양 → "루" 알파벳 ru처럼 🔤',
    examples:[{word:'ルール',meaning:'규칙 (rule)'},{word:'ルーム',meaning:'룸 (room)'}]},
  'レ': { romaji:'re',  korean:'레', english:'reh',   type:'katakana', tip:'알파벳 L처럼 생겼어요! L → レ → "레" 🔤',
    examples:[{word:'レストラン',meaning:'레스토랑 (restaurant)'},{word:'レポート',meaning:'리포트 (report)'}]},
  'ロ': { romaji:'ro',  korean:'로', english:'roh',   type:'katakana', tip:'사각형(□) 모양 → "로" 로봇 방 🤖',
    examples:[{word:'ロボット',meaning:'로봇 (robot)'},{word:'ロシア',meaning:'러시아 (Russia)'}]},

  'ワ': { romaji:'wa',  korean:'와', english:'wah',   type:'katakana', tip:'알파벳 W처럼 → "와" 와우! W',
    examples:[{word:'ワイン',meaning:'와인 (wine)'},{word:'ワールド',meaning:'월드 (world)'}]},
  'ヲ': { romaji:'wo',  korean:'오', english:'oh',    type:'katakana', tip:'조사로만 쓰이는 가타가나 → 발음은 "오" → 특별한 글자 ⭐',
    examples:[{word:'(조사로만 사용)',meaning:'particle (object marker)'}]},
  'ン': { romaji:'n',   korean:'음', english:'n/ng',  type:'katakana', tip:'ソ와 비슷하지만 각도가 달라요 → "응" 콧소리 👃',
    examples:[{word:'テレビン',meaning:'테레빈 (turpentine)'},{word:'ランチ',meaning:'점심 (lunch)'}]},

  // ─────────────────── 가타가나 탁음 (濁音) ───────────────────
  'ガ': { romaji:'ga',  korean:'가', english:'gah',   type:'katakana_dakuten', tip:'カ에 탁점(゛)→"가"! ガム(껌)의 "가" 🍬',
    examples:[{word:'ガム',meaning:'껌 (gum)'},{word:'ガレージ',meaning:'차고 (garage)'}]},
  'ギ': { romaji:'gi',  korean:'기', english:'gee',   type:'katakana_dakuten', tip:'キ에 탁점(゛)→"기"! ギター(기타)의 "기" 🎸',
    examples:[{word:'ギター',meaning:'기타 (guitar)'},{word:'ギリシャ',meaning:'그리스 (Greece)'}]},
  'グ': { romaji:'gu',  korean:'구', english:'goo',   type:'katakana_dakuten', tip:'ク에 탁점(゛)→"구"! グーグル(구글)의 "구" 🔍',
    examples:[{word:'グラス',meaning:'글라스/잔 (glass)'},{word:'グーグル',meaning:'구글 (Google)'}]},
  'ゲ': { romaji:'ge',  korean:'게', english:'geh',   type:'katakana_dakuten', tip:'ケ에 탁점(゛)→"게"! ゲーム(게임)의 "게" 🎮',
    examples:[{word:'ゲーム',meaning:'게임 (game)'},{word:'ゲスト',meaning:'게스트 (guest)'}]},
  'ゴ': { romaji:'go',  korean:'고', english:'goh',   type:'katakana_dakuten', tip:'コ에 탁점(゛)→"고"! ゴルフ(골프)의 "고" ⛳',
    examples:[{word:'ゴルフ',meaning:'골프 (golf)'},{word:'ゴール',meaning:'골 (goal)'}]},

  'ザ': { romaji:'za',  korean:'자', english:'zah',   type:'katakana_dakuten', tip:'サ에 탁점(゛)→"자"! ザッピング(채널 돌리기)의 "자" 📺',
    examples:[{word:'ザッピング',meaning:'채널 돌리기 (zapping)'},{word:'ザンビア',meaning:'잠비아 (Zambia)'}]},
  'ジ': { romaji:'ji',  korean:'지', english:'jee',   type:'katakana_dakuten', tip:'シ에 탁점(゛)→"지"! ジュース(주스)의 "지" 🧃',
    examples:[{word:'ジュース',meaning:'주스 (juice)'},{word:'ジャケット',meaning:'재킷 (jacket)'}]},
  'ズ': { romaji:'zu',  korean:'즈', english:'zoo',   type:'katakana_dakuten', tip:'ス에 탁점(゛)→"즈"! ズボン(바지)의 "즈" 👖',
    examples:[{word:'ズボン',meaning:'바지 (pants)'},{word:'ズーム',meaning:'줌 (zoom)'}]},
  'ゼ': { romaji:'ze',  korean:'제', english:'zeh',   type:'katakana_dakuten', tip:'セ에 탁점(゛)→"제"! ゼリー(젤리)의 "제" 🍮',
    examples:[{word:'ゼリー',meaning:'젤리 (jelly)'},{word:'ゼロ',meaning:'제로/0 (zero)'}]},
  'ゾ': { romaji:'zo',  korean:'조', english:'zoh',   type:'katakana_dakuten', tip:'ソ에 탁점(゛)→"조"! ゾンビ(좀비)의 "조" 🧟',
    examples:[{word:'ゾーン',meaning:'존/구역 (zone)'},{word:'ゾンビ',meaning:'좀비 (zombie)'}]},

  'ダ': { romaji:'da',  korean:'다', english:'dah',   type:'katakana_dakuten', tip:'タ에 탁점(゛)→"다"! ダンス(댄스)의 "다" 💃',
    examples:[{word:'ダンス',meaning:'댄스 (dance)'},{word:'ダイヤ',meaning:'다이아 (diamond)'}]},
  'ヂ': { romaji:'ji',  korean:'지', english:'jee',   type:'katakana_dakuten', tip:'チ에 탁점(゛)→"지"! ジ와 같은 발음 — 거의 안 씀 📝',
    examples:[{word:'(드물게 사용)',meaning:'rarely used, same sound as ジ'}]},
  'ヅ': { romaji:'zu',  korean:'즈', english:'zoo',   type:'katakana_dakuten', tip:'ツ에 탁점(゛)→"즈"! ズ와 같은 발음 — 거의 안 씀 📝',
    examples:[{word:'(드물게 사용)',meaning:'rarely used, same sound as ズ'}]},
  'デ': { romaji:'de',  korean:'데', english:'deh',   type:'katakana_dakuten', tip:'テ에 탁점(゛)→"데"! デザイン(디자인)의 "데" 🎨',
    examples:[{word:'デザイン',meaning:'디자인 (design)'},{word:'デート',meaning:'데이트 (date)'}]},
  'ド': { romaji:'do',  korean:'도', english:'doh',   type:'katakana_dakuten', tip:'ト에 탁점(゛)→"도"! ドア(문)의 "도" 🚪',
    examples:[{word:'ドア',meaning:'문 (door)'},{word:'ドラマ',meaning:'드라마 (drama)'}]},

  'バ': { romaji:'ba',  korean:'바', english:'bah',   type:'katakana_dakuten', tip:'ハ에 탁점(゛)→"바"! バス(버스)의 "바" 🚌',
    examples:[{word:'バス',meaning:'버스 (bus)'},{word:'バナナ',meaning:'바나나 (banana)'}]},
  'ビ': { romaji:'bi',  korean:'비', english:'bee',   type:'katakana_dakuten', tip:'ヒ에 탁점(゛)→"비"! ビール(맥주)의 "비" 🍺',
    examples:[{word:'ビール',meaning:'맥주 (beer)'},{word:'ビデオ',meaning:'비디오 (video)'}]},
  'ブ': { romaji:'bu',  korean:'부', english:'boo',   type:'katakana_dakuten', tip:'フ에 탁점(゛)→"부"! ブログ(블로그)의 "부" 💻',
    examples:[{word:'ブログ',meaning:'블로그 (blog)'},{word:'ブランド',meaning:'브랜드 (brand)'}]},
  'ベ': { romaji:'be',  korean:'베', english:'beh',   type:'katakana_dakuten', tip:'ヘ에 탁점(゛)→"베"! ベッド(침대)의 "베" 🛏️',
    examples:[{word:'ベッド',meaning:'침대 (bed)'},{word:'ベルト',meaning:'벨트 (belt)'}]},
  'ボ': { romaji:'bo',  korean:'보', english:'boh',   type:'katakana_dakuten', tip:'ホ에 탁점(゛)→"보"! ボール(공)의 "보" ⚽',
    examples:[{word:'ボール',meaning:'공 (ball)'},{word:'ボタン',meaning:'버튼 (button)'}]},

  // ─────────────────── 가타가나 반탁음 (半濁音) ───────────────────
  'パ': { romaji:'pa',  korean:'파', english:'pah',   type:'katakana_handakuten', tip:'ハ에 반탁점(゜)→"파"! パスポート(여권)의 "파" 🛂',
    examples:[{word:'パスポート',meaning:'여권 (passport)'},{word:'パーティー',meaning:'파티 (party)'}]},
  'ピ': { romaji:'pi',  korean:'피', english:'pee',   type:'katakana_handakuten', tip:'ヒ에 반탁점(゜)→"피"! ピザ(피자)의 "피" 🍕',
    examples:[{word:'ピザ',meaning:'피자 (pizza)'},{word:'ピアノ',meaning:'피아노 (piano)'}]},
  'プ': { romaji:'pu',  korean:'푸', english:'poo',   type:'katakana_handakuten', tip:'フ에 반탁점(゜)→"푸"! プール(수영장)의 "푸" 🏊',
    examples:[{word:'プール',meaning:'수영장 (pool)'},{word:'プリンター',meaning:'프린터 (printer)'}]},
  'ペ': { romaji:'pe',  korean:'페', english:'peh',   type:'katakana_handakuten', tip:'ヘ에 반탁점(゜)→"페"! ペット(반려동물)의 "페" 🐾',
    examples:[{word:'ペット',meaning:'반려동물 (pet)'},{word:'ペン',meaning:'펜 (pen)'}]},
  'ポ': { romaji:'po',  korean:'포', english:'poh',   type:'katakana_handakuten', tip:'ホ에 반탁점(゜)→"포"! ポケモン(포켓몬)의 "포" 🎮',
    examples:[{word:'ポケモン',meaning:'포켓몬 (Pokémon)'},{word:'ポスター',meaning:'포스터 (poster)'}]},

  // ─────────────────── 가타가나 요음 ───────────────────
  'キャ': { romaji:'kya', korean:'캬', english:'kyah', type:'katakana_yoon', tip:'キ+ャ→"캬"! キャラクター(캐릭터)의 "캬" 🎭',
    examples:[{word:'キャラクター',meaning:'캐릭터 (character)'},{word:'キャンセル',meaning:'취소 (cancel)'}]},
  'キュ': { romaji:'kyu', korean:'큐', english:'kyoo', type:'katakana_yoon', tip:'キ+ュ→"큐"! キューブ(큐브)의 "큐" 🎲',
    examples:[{word:'キュート',meaning:'귀엽다 (cute)'},{word:'キュービック',meaning:'큐빅 (cubic)'}]},
  'キョ': { romaji:'kyo', korean:'쿄', english:'kyoh', type:'katakana_yoon', tip:'キ+ョ→"쿄"! キョウト(교토)의 "쿄" ⛩️',
    examples:[{word:'キョウト(京都)',meaning:'교토 (Kyoto)'}]},

  'シャ': { romaji:'sha', korean:'샤', english:'shah', type:'katakana_yoon', tip:'シ+ャ→"샤"! シャワー(샤워)의 "샤" 🚿',
    examples:[{word:'シャワー',meaning:'샤워 (shower)'},{word:'シャンプー',meaning:'샴푸 (shampoo)'}]},
  'シュ': { romaji:'shu', korean:'슈', english:'shoo', type:'katakana_yoon', tip:'シ+ュ→"슈"! シュークリーム(슈크림)의 "슈" 🍰',
    examples:[{word:'シュークリーム',meaning:'슈크림 (cream puff)'},{word:'シュート',meaning:'슛 (shoot)'}]},
  'ショ': { romaji:'sho', korean:'쇼', english:'shoh', type:'katakana_yoon', tip:'シ+ョ→"쇼"! ショッピング(쇼핑)의 "쇼" 🛍️',
    examples:[{word:'ショッピング',meaning:'쇼핑 (shopping)'},{word:'ショー',meaning:'쇼 (show)'}]},

  'チャ': { romaji:'cha', korean:'차', english:'chah', type:'katakana_yoon', tip:'チ+ャ→"차"! チャンス(찬스/기회)의 "차" 🎯',
    examples:[{word:'チャンス',meaning:'찬스/기회 (chance)'},{word:'チャンネル',meaning:'채널 (channel)'}]},
  'チュ': { romaji:'chu', korean:'추', english:'choo', type:'katakana_yoon', tip:'チ+ュ→"추"! チューブ(튜브)의 "추" 🧴',
    examples:[{word:'チューリップ',meaning:'튤립 (tulip)'},{word:'チューブ',meaning:'튜브 (tube)'}]},
  'チョ': { romaji:'cho', korean:'쵸', english:'choh', type:'katakana_yoon', tip:'チ+ョ→"쵸"! チョコレート(초콜릿)의 "쵸" 🍫',
    examples:[{word:'チョコレート',meaning:'초콜릿 (chocolate)'},{word:'チョコ',meaning:'초코 (choco)'}]},

  'ニャ': { romaji:'nya', korean:'냐', english:'nyah', type:'katakana_yoon', tip:'ニ+ャ→"냐"! ニャー는 가타가나로 쓴 고양이 울음 🐱',
    examples:[{word:'ニャンコ',meaning:'고양이(애칭) (kitty)'}]},
  'ニュ': { romaji:'nyu', korean:'뉴', english:'nyoo', type:'katakana_yoon', tip:'ニ+ュ→"뉴"! ニュース(뉴스)의 "뉴" 📰',
    examples:[{word:'ニュース',meaning:'뉴스 (news)'},{word:'ニューヨーク',meaning:'뉴욕 (New York)'}]},
  'ニョ': { romaji:'nyo', korean:'뇨', english:'nyoh', type:'katakana_yoon', tip:'ニ+ョ→"뇨"! 드물게 쓰이는 요음 📝',
    examples:[{word:'ニョッキ',meaning:'뇨키 (gnocchi)'}]},

  'ヒャ': { romaji:'hya', korean:'햐', english:'hyah', type:'katakana_yoon', tip:'ヒ+ャ→"햐"! ヒャク(백=100)의 "햐" 💯',
    examples:[{word:'ヒャク',meaning:'100 (hundred)'}]},
  'ヒュ': { romaji:'hyu', korean:'휴', english:'hyoo', type:'katakana_yoon', tip:'ヒ+ュ→"휴"! ヒューマン(휴먼)의 "휴" 👤',
    examples:[{word:'ヒューズ',meaning:'퓨즈 (fuse)'},{word:'ヒューストン',meaning:'휴스턴 (Houston)'}]},
  'ヒョ': { romaji:'hyo', korean:'효', english:'hyoh', type:'katakana_yoon', tip:'ヒ+ョ→"효"! ドラゴンの소리처럼 강렬! ヒョウ(표범) 🐆',
    examples:[{word:'ヒョウ',meaning:'표범 (leopard)'}]},

  'ミャ': { romaji:'mya', korean:'먀', english:'myah', type:'katakana_yoon', tip:'ミ+ャ→"먀"! 드물게 쓰이는 요음 📝',
    examples:[{word:'ミャンマー',meaning:'미얀마 (Myanmar)'}]},
  'ミュ': { romaji:'myu', korean:'뮤', english:'myoo', type:'katakana_yoon', tip:'ミ+ュ→"뮤"! ミュージック(뮤직)의 "뮤" 🎵',
    examples:[{word:'ミュージック',meaning:'뮤직 (music)'},{word:'ミュージアム',meaning:'뮤지엄 (museum)'}]},
  'ミョ': { romaji:'myo', korean:'묘', english:'myoh', type:'katakana_yoon', tip:'ミ+ョ→"묘"! 드물게 쓰이는 요음 📝',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},

  'リャ': { romaji:'rya', korean:'랴', english:'ryah', type:'katakana_yoon', tip:'リ+ャ→"랴"! 드물게 쓰이는 요음 📝',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},
  'リュ': { romaji:'ryu', korean:'류', english:'ryoo', type:'katakana_yoon', tip:'リ+ュ→"류"! リュック(배낭)의 "류" 🎒',
    examples:[{word:'リュック',meaning:'배낭 (backpack)'},{word:'リュクサック',meaning:'배낭 (rucksack)'}]},
  'リョ': { romaji:'ryo', korean:'료', english:'ryoh', type:'katakana_yoon', tip:'リ+ョ→"료"! リョコウ(여행)의 "료" ✈️',
    examples:[{word:'リョーマ',meaning:'료마 (proper name)'}]},

  'ギャ': { romaji:'gya', korean:'갸', english:'gyah', type:'katakana_yoon', tip:'ギ+ャ→"갸"! ギャグ(개그)의 "갸" 😂',
    examples:[{word:'ギャップ',meaning:'갭/차이 (gap)'},{word:'ギャラリー',meaning:'갤러리 (gallery)'}]},
  'ギュ': { romaji:'gyu', korean:'규', english:'gyoo', type:'katakana_yoon', tip:'ギ+ュ→"규"! ギュッと(꽉) 쥐는 소리 💪',
    examples:[{word:'ギュっと',meaning:'꽉 (tightly)'}]},
  'ギョ': { romaji:'gyo', korean:'교', english:'gyoh', type:'katakana_yoon', tip:'ギ+ョ→"교"! ギョウザ(만두)의 "교" 🥟',
    examples:[{word:'ギョーザ',meaning:'만두 (gyoza)'}]},

  'ジャ': { romaji:'ja',  korean:'자', english:'jah',  type:'katakana_yoon', tip:'ジ+ャ→"자"! ジャズ(재즈)의 "자" 🎷',
    examples:[{word:'ジャム',meaning:'잼 (jam)'},{word:'ジャズ',meaning:'재즈 (jazz)'}]},
  'ジュ': { romaji:'ju',  korean:'주', english:'joo',  type:'katakana_yoon', tip:'ジ+ュ→"주"! ジュース(주스)의 "주" 🧃',
    examples:[{word:'ジュース',meaning:'주스 (juice)'},{word:'ジュエリー',meaning:'주얼리 (jewelry)'}]},
  'ジョ': { romaji:'jo',  korean:'조', english:'joh',  type:'katakana_yoon', tip:'ジ+ョ→"조"! ジョギング(조깅)의 "조" 🏃',
    examples:[{word:'ジョグ',meaning:'조깅 (jog)'},{word:'ジョーク',meaning:'농담 (joke)'}]},

  'ビャ': { romaji:'bya', korean:'뱌', english:'byah', type:'katakana_yoon', tip:'ビ+ャ→"뱌"! 드물게 쓰이는 요음 📝',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},
  'ビュ': { romaji:'byu', korean:'뷰', english:'byoo', type:'katakana_yoon', tip:'ビ+ュ→"뷰"! ビューティー(뷰티)의 "뷰" 💄',
    examples:[{word:'ビュッフェ',meaning:'뷔페 (buffet)'},{word:'ビュー',meaning:'뷰/전망 (view)'}]},
  'ビョ': { romaji:'byo', korean:'뵤', english:'byoh', type:'katakana_yoon', tip:'ビ+ョ→"뵤"! ビョウイン(병원) — 히라가나 びょ와 같음 🏥',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},

  'ピャ': { romaji:'pya', korean:'퍄', english:'pyah', type:'katakana_yoon', tip:'ピ+ャ→"퍄"! 드물게 쓰이는 요음 📝',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},
  'ピュ': { romaji:'pyu', korean:'퓨', english:'pyoo', type:'katakana_yoon', tip:'ピ+ュ→"퓨"! ピュア(퓨어/순수)의 "퓨" 💧',
    examples:[{word:'ピュア',meaning:'순수 (pure)'},{word:'コンピュータ',meaning:'컴퓨터 (computer)'}]},
  'ピョ': { romaji:'pyo', korean:'표', english:'pyoh', type:'katakana_yoon', tip:'ピ+ョ→"표"! ぴょんぴょん의 가타가나 표기 — 깡충깡충 🐰',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},
});

if (typeof module !== 'undefined') {
  module.exports = { KANA_MAP };
}
