// ============================================================
// KANA DATA - 히라가나 + 가타가나 (탁음·반탁음·요음 포함)
// 각 항목: { kana, romaji, korean, english, type, examples[] }
// ============================================================

const LEVELS = [
  {
    id: 1,
    name: 'Level 1',
    title: '히라가나 기본',
    subtitle: 'あ행 ~ ん (46자 전체)',
    desc: '히라가나 46자를 한 번에! 일본어의 기초를 완성하자.',
    type: 'hiragana',
    chars: ['あ','い','う','え','お','か','き','く','け','こ','さ','し','す','せ','そ','た','ち','つ','て','と','な','に','ぬ','ね','の','は','ひ','ふ','へ','ほ','ま','み','む','め','も','や','ゆ','よ','ら','り','る','れ','ろ','わ','を','ん'],
    unlockXP: 0
  },
  {
    id: 2,
    name: 'Level 2',
    title: '히라가나 탁음+반탁음',
    subtitle: 'が행~ぼ행 + ぱ행 (25자)',
    desc: '탁점(゛)·반탁점(゜)이 붙는 25자를 마스터!',
    type: 'hiragana_dakuten',
    chars: ['が','ぎ','ぐ','げ','ご','ざ','じ','ず','ぜ','ぞ','だ','ぢ','づ','で','ど','ば','び','ぶ','べ','ぼ','ぱ','ぴ','ぷ','ぺ','ぽ'],
    unlockXP: 400
  },
  {
    id: 3,
    name: 'Level 3',
    title: '히라가나 요음',
    subtitle: 'きゃ~ぴょ (33자)',
    desc: '두 글자가 합쳐진 요음! 실용 단어가 쏟아진다.',
    type: 'hiragana_yoon',
    chars: ['きゃ','きゅ','きょ','しゃ','しゅ','しょ','ちゃ','ちゅ','ちょ','にゃ','にゅ','にょ','ひゃ','ひゅ','ひょ','みゃ','みゅ','みょ','りゃ','りゅ','りょ','ぎゃ','ぎゅ','ぎょ','じゃ','じゅ','じょ','びゃ','びゅ','びょ','ぴゃ','ぴゅ','ぴょ'],
    unlockXP: 800
  },
  {
    id: 4,
    name: 'Level 4',
    title: '가타가나 기본',
    subtitle: 'ア행 ~ ン (46자 전체)',
    desc: '외래어를 표기하는 가타가나 46자 한 번에 완성!',
    type: 'katakana',
    chars: ['ア','イ','ウ','エ','オ','カ','キ','ク','ケ','コ','サ','シ','ス','セ','ソ','タ','チ','ツ','テ','ト','ナ','ニ','ヌ','ネ','ノ','ハ','ヒ','フ','ヘ','ホ','マ','ミ','ム','メ','モ','ヤ','ユ','ヨ','ラ','リ','ル','レ','ロ','ワ','ヲ','ン'],
    unlockXP: 1300
  },
  {
    id: 5,
    name: 'Level 5',
    title: '가타가나 탁음+반탁음',
    subtitle: 'ガ행~ボ행 + パ행 (25자)',
    desc: '가타가나에도 탁점·반탁점! 외래어 표현력 UP!',
    type: 'katakana_dakuten',
    chars: ['ガ','ギ','グ','ゲ','ゴ','ザ','ジ','ズ','ゼ','ゾ','ダ','ヂ','ヅ','デ','ド','バ','ビ','ブ','ベ','ボ','パ','ピ','プ','ペ','ポ'],
    unlockXP: 1800
  },
  {
    id: 6,
    name: 'Level 6',
    title: '가타가나 요음',
    subtitle: 'キャ~ピョ (33자)',
    desc: '가타가나 요음으로 외래어 마스터!',
    type: 'katakana_yoon',
    chars: ['キャ','キュ','キョ','シャ','シュ','ショ','チャ','チュ','チョ','ニャ','ニュ','ニョ','ヒャ','ヒュ','ヒョ','ミャ','ミュ','ミョ','リャ','リュ','リョ','ギャ','ギュ','ギョ','ジャ','ジュ','ジョ','ビャ','ビュ','ビョ','ピャ','ピュ','ピョ'],
    unlockXP: 2400
  },
  {
    id: 7,
    name: 'Level 7',
    title: '종합 복습 — 기본 히라가나+가타가나',
    subtitle: '히라가나 46자 + 가타가나 46자 (92자)',
    desc: '히라가나와 가타가나 기본자를 함께 복습! 대조 연습으로 실력 굳히기.',
    type: 'hiragana',
    chars: ['あ','い','う','え','お','か','き','く','け','こ','さ','し','す','せ','そ','た','ち','つ','て','と','な','に','ぬ','ね','の','は','ひ','ふ','へ','ほ','ま','み','む','め','も','や','ゆ','よ','ら','り','る','れ','ろ','わ','を','ん','ア','イ','ウ','エ','オ','カ','キ','ク','ケ','コ','サ','シ','ス','セ','ソ','タ','チ','ツ','テ','ト','ナ','ニ','ヌ','ネ','ノ','ハ','ヒ','フ','ヘ','ホ','マ','ミ','ム','メ','モ','ヤ','ユ','ヨ','ラ','リ','ル','レ','ロ','ワ','ヲ','ン'],
    unlockXP: 3000
  },
  {
    id: 8,
    name: 'Level 8',
    title: '예외·특수 종합',
    subtitle: '탁음+반탁음+요음 전체 (116자)',
    desc: '탁음, 반탁음, 요음을 모두 한 번에! 완전 정복 직전 단계.',
    type: 'hiragana_dakuten',
    chars: ['が','ぎ','ぐ','げ','ご','ざ','じ','ず','ぜ','ぞ','だ','ぢ','づ','で','ど','ば','び','ぶ','べ','ぼ','ぱ','ぴ','ぷ','ぺ','ぽ','きゃ','きゅ','きょ','しゃ','しゅ','しょ','ちゃ','ちゅ','ちょ','にゃ','にゅ','にょ','ひゃ','ひゅ','ひょ','みゃ','みゅ','みょ','りゃ','りゅ','りょ','ぎゃ','ぎゅ','ぎょ','じゃ','じゅ','じょ','びゃ','びゅ','びょ','ぴゃ','ぴゅ','ぴょ','ガ','ギ','グ','ゲ','ゴ','ザ','ジ','ズ','ゼ','ゾ','ダ','ヂ','ヅ','デ','ド','バ','ビ','ブ','ベ','ボ','パ','ピ','プ','ペ','ポ','キャ','キュ','キョ','シャ','シュ','ショ','チャ','チュ','チョ','ニャ','ニュ','ニョ','ヒャ','ヒュ','ヒョ','ミャ','ミュ','ミョ','リャ','リュ','リョ','ギャ','ギュ','ギョ','ジャ','ジュ','ジョ','ビャ','ビュ','ビョ','ピャ','ピュ','ピョ'],
    unlockXP: 3700
  },
  {
    id: 9,
    name: 'Level 9',
    title: '특수 박자',
    subtitle: 'っ·ッ·ー·장음 패턴 (8가지)',
    desc: '촉음·장음부·장음 패턴! 실제 일본어 읽기의 핵심 규칙을 마스터하자.',
    type: 'special',
    chars: ['っ','ッ','ー','おう','えい','ああ','いい','うう'],
    unlockXP: 4200
  },
  {
    id: 10,
    name: 'Level 10',
    title: '외래어 가타카나 확장',
    subtitle: 'ファ·ティ·ヴ 등 (20가지)',
    desc: '외국어 발음을 표기하는 특수 가타카나 조합! 현대 일본어 필수.',
    type: 'katakana_extended',
    chars: ['ファ','フィ','フェ','フォ','ティ','ディ','トゥ','ドゥ','ウィ','ウェ','ウォ','チェ','シェ','ジェ','ヴ','ヴァ','ヴィ','ヴェ','ヴォ','イェ'],
    unlockXP: 5000
  },
  {
    id: 11,
    name: 'Level 11',
    title: '조사 읽기 예외',
    subtitle: 'は→wa · へ→e · を→o',
    desc: '표기와 발음이 다른 조사 3개! 문장 읽기의 함정을 완전히 해결.',
    type: 'particle',
    chars: ['は_p','へ_p','を_p'],
    unlockXP: 5800
  },
  {
    id: 12,
    name: 'Level 12',
    title: '⭐ 전체 복습',
    subtitle: '모든 가나 + 특수 박자 + 외래어',
    desc: '최종 보스! 모든 가나를 랜덤 셔플로 완전 정복!',
    type: 'hiragana',
    chars: [],
    unlockXP: 6600
  }
];

// ----------------------------------------------------------------
// 개별 가나 데이터
// ----------------------------------------------------------------
const KANA_MAP = {
  // ─────────────────── 히라가나 기본 ───────────────────
  'あ': { romaji:'a',   korean:'아', english:'ah',    type:'hiragana',
    examples:[{word:'あか',meaning:'빨강 (red)'},{word:'あさ',meaning:'아침 (morning)'},{word:'あに',meaning:'오빠/형 (older brother)'},{word:'あき',meaning:'가을 (autumn)'},{word:'あおい',meaning:'파랗다 (blue)'},{word:'あいさつ',meaning:'인사 (greeting)'}]},
  'い': { romaji:'i',   korean:'이', english:'ee',    type:'hiragana',
    examples:[{word:'いぬ',meaning:'개 (dog)'},{word:'いえ',meaning:'집 (house)'},{word:'いち',meaning:'1 (one)'},{word:'いす',meaning:'의자 (chair)'},{word:'いもうと',meaning:'여동생 (younger sister)'},{word:'いま',meaning:'지금 (now)'}]},
  'う': { romaji:'u',   korean:'우', english:'oo',    type:'hiragana',
    examples:[{word:'うみ',meaning:'바다 (sea)'},{word:'うた',meaning:'노래 (song)'},{word:'うで',meaning:'팔 (arm)'},{word:'うさぎ',meaning:'토끼 (rabbit)'},{word:'うまい',meaning:'맛있다/잘한다 (delicious/skilled)'},{word:'うれしい',meaning:'기쁘다 (happy)'}]},
  'え': { romaji:'e',   korean:'에', english:'eh',    type:'hiragana',
    examples:[{word:'えき',meaning:'역 (station)'},{word:'えほん',meaning:'그림책 (picture book)'},{word:'えいご',meaning:'영어 (English)'},{word:'えんぴつ',meaning:'연필 (pencil)'},{word:'えがお',meaning:'웃는 얼굴 (smile)'},{word:'えいが',meaning:'영화 (movie)'}]},
  'お': { romaji:'o',   korean:'오', english:'oh',    type:'hiragana',
    examples:[{word:'おかあさん',meaning:'어머니 (mother)'},{word:'おとうさん',meaning:'아버지 (father)'},{word:'おちゃ',meaning:'녹차 (green tea)'},{word:'おはよう',meaning:'안녕하세요 (good morning)'},{word:'おかし',meaning:'과자 (sweets)'},{word:'おんがく',meaning:'음악 (music)'}]},

  'か': { romaji:'ka',  korean:'카', english:'kah',   type:'hiragana',
    examples:[{word:'かさ',meaning:'우산 (umbrella)'},{word:'かわ',meaning:'강 (river)'},{word:'かお',meaning:'얼굴 (face)'},{word:'かみ',meaning:'종이/머리 (paper/hair)'},{word:'かいもの',meaning:'쇼핑 (shopping)'},{word:'かんたん',meaning:'간단함 (easy)'}]},
  'き': { romaji:'ki',  korean:'키', english:'key',   type:'hiragana',
    examples:[{word:'きって',meaning:'우표 (stamp)'},{word:'きのこ',meaning:'버섯 (mushroom)'},{word:'きれい',meaning:'예쁘다 (beautiful)'},{word:'きもの',meaning:'기모노 (kimono)'},{word:'きせつ',meaning:'계절 (season)'},{word:'きんようび',meaning:'금요일 (Friday)'}]},
  'く': { romaji:'ku',  korean:'쿠', english:'koo',   type:'hiragana',
    examples:[{word:'くも',meaning:'구름 (cloud)'},{word:'くち',meaning:'입 (mouth)'},{word:'くに',meaning:'나라 (country)'},{word:'くるま',meaning:'자동차 (car)'},{word:'くつ',meaning:'신발 (shoes)'},{word:'くだもの',meaning:'과일 (fruit)'}]},
  'け': { romaji:'ke',  korean:'케', english:'keh',   type:'hiragana',
    examples:[{word:'けさ',meaning:'오늘 아침 (this morning)'},{word:'けむり',meaning:'연기 (smoke)'},{word:'げんき',meaning:'건강 (healthy)'},{word:'けが',meaning:'부상 (injury)'},{word:'けっこん',meaning:'결혼 (marriage)'},{word:'けいたい',meaning:'휴대폰 (cell phone)'}]},
  'こ': { romaji:'ko',  korean:'코', english:'koh',   type:'hiragana',
    examples:[{word:'こえ',meaning:'목소리 (voice)'},{word:'ここ',meaning:'여기 (here)'},{word:'こども',meaning:'어린이 (child)'},{word:'こうえん',meaning:'공원 (park)'},{word:'こめ',meaning:'쌀 (rice)'},{word:'こたえ',meaning:'대답 (answer)'}]},

  'さ': { romaji:'sa',  korean:'사', english:'sah',   type:'hiragana',
    examples:[{word:'さかな',meaning:'물고기 (fish)'},{word:'さくら',meaning:'벚꽃 (cherry blossom)'},{word:'さとう',meaning:'설탕 (sugar)'},{word:'さいふ',meaning:'지갑 (wallet)'},{word:'さんぽ',meaning:'산책 (walk)'},{word:'さびしい',meaning:'외롭다 (lonely)'}]},
  'し': { romaji:'shi', korean:'시', english:'shee',  type:'hiragana',
    examples:[{word:'しろ',meaning:'하얀색 (white)'},{word:'しごと',meaning:'일 (work)'},{word:'しんかんせん',meaning:'신칸센 (bullet train)'},{word:'しお',meaning:'소금 (salt)'},{word:'しあわせ',meaning:'행복 (happiness)'},{word:'しぜん',meaning:'자연 (nature)'}]},
  'す': { romaji:'su',  korean:'스', english:'soo',   type:'hiragana',
    examples:[{word:'すし',meaning:'초밥 (sushi)'},{word:'すいか',meaning:'수박 (watermelon)'},{word:'すき',meaning:'좋아함 (like)'},{word:'すずしい',meaning:'시원하다 (cool)'},{word:'すいえい',meaning:'수영 (swimming)'},{word:'すみません',meaning:'실례합니다 (excuse me)'}]},
  'せ': { romaji:'se',  korean:'세', english:'seh',   type:'hiragana',
    examples:[{word:'せかい',meaning:'세계 (world)'},{word:'せんせい',meaning:'선생님 (teacher)'},{word:'せっけん',meaning:'비누 (soap)'},{word:'せまい',meaning:'좁다 (narrow)'},{word:'せいと',meaning:'학생 (student)'},{word:'せつめい',meaning:'설명 (explanation)'}]},
  'そ': { romaji:'so',  korean:'소', english:'soh',   type:'hiragana',
    examples:[{word:'そら',meaning:'하늘 (sky)'},{word:'そと',meaning:'바깥 (outside)'},{word:'そば',meaning:'소바 (soba noodles)'},{word:'そうじ',meaning:'청소 (cleaning)'},{word:'そつぎょう',meaning:'졸업 (graduation)'},{word:'そして',meaning:'그리고 (and then)'}]},

  // ─── た행 ───
  'た': { romaji:'ta',  korean:'타', english:'tah',   type:'hiragana',
    examples:[{word:'たこ',meaning:'문어 (octopus)'},{word:'たまご',meaning:'계란 (egg)'},{word:'ともだち',meaning:'친구 (friend)'},{word:'たのしい',meaning:'즐겁다 (fun)'},{word:'たべもの',meaning:'음식 (food)'},{word:'たいへん',meaning:'힘들다 (tough/serious)'}]},
  'ち': { romaji:'chi', korean:'치', english:'chee',  type:'hiragana',
    examples:[{word:'ちず',meaning:'지도 (map)'},{word:'ちから',meaning:'힘 (strength)'},{word:'ちかてつ',meaning:'지하철 (subway)'},{word:'ちいさい',meaning:'작다 (small)'},{word:'ちょっと',meaning:'잠깐 (a little/wait)'},{word:'ちかい',meaning:'가깝다 (near)'}]},
  'つ': { romaji:'tsu', korean:'츠', english:'tsoo',  type:'hiragana',
    examples:[{word:'つき',meaning:'달 (moon)'},{word:'つくえ',meaning:'책상 (desk)'},{word:'つり',meaning:'낚시 (fishing)'},{word:'つめたい',meaning:'차갑다 (cold)'},{word:'つかれた',meaning:'피곤하다 (tired)'},{word:'つよい',meaning:'강하다 (strong)'}]},
  'て': { romaji:'te',  korean:'테', english:'teh',   type:'hiragana',
    examples:[{word:'てがみ',meaning:'편지 (letter)'},{word:'てんき',meaning:'날씨 (weather)'},{word:'てんぷら',meaning:'튀김 (tempura)'},{word:'てすと',meaning:'시험 (test)'},{word:'てぶくろ',meaning:'장갑 (gloves)'},{word:'てつだう',meaning:'돕다 (help)'}]},
  'と': { romaji:'to',  korean:'토', english:'toh',   type:'hiragana',
    examples:[{word:'とり',meaning:'새 (bird)'},{word:'とけい',meaning:'시계 (clock)'},{word:'としょかん',meaning:'도서관 (library)'},{word:'ともだち',meaning:'친구 (friend)'},{word:'とおい',meaning:'멀다 (far)'},{word:'とんかつ',meaning:'돈가스 (tonkatsu)'}]},

  // ─── な행 ───
  'な': { romaji:'na',  korean:'나', english:'nah',   type:'hiragana',
    examples:[{word:'なまえ',meaning:'이름 (name)'},{word:'なつ',meaning:'여름 (summer)'},{word:'なに',meaning:'무엇 (what)'},{word:'なか',meaning:'안/중간 (inside)'},{word:'ながい',meaning:'길다 (long)'},{word:'なるほど',meaning:'그렇구나 (I see)'}]},
  'に': { romaji:'ni',  korean:'니', english:'nee',   type:'hiragana',
    examples:[{word:'にほん',meaning:'일본 (Japan)'},{word:'にわ',meaning:'정원 (garden)'},{word:'にじ',meaning:'무지개 (rainbow)'},{word:'にもつ',meaning:'짐 (luggage)'},{word:'にっき',meaning:'일기 (diary)'},{word:'にんじん',meaning:'당근 (carrot)'}]},
  'ぬ': { romaji:'nu',  korean:'누', english:'noo',   type:'hiragana',
    examples:[{word:'ぬの',meaning:'천/옷감 (cloth)'},{word:'ぬりえ',meaning:'색칠 공부 (coloring book)'},{word:'ぬいぐるみ',meaning:'봉제 인형 (stuffed toy)'},{word:'ぬれる',meaning:'젖다 (get wet)'},{word:'ぬく',meaning:'뽑다 (pull out)'}]},
  'ね': { romaji:'ne',  korean:'네', english:'neh',   type:'hiragana',
    examples:[{word:'ねこ',meaning:'고양이 (cat)'},{word:'ねむい',meaning:'졸리다 (sleepy)'},{word:'ねつ',meaning:'열 (fever)'},{word:'ねがい',meaning:'소원 (wish)'},{word:'ねだん',meaning:'가격 (price)'},{word:'ねんれい',meaning:'나이 (age)'}]},
  'の': { romaji:'no',  korean:'노', english:'noh',   type:'hiragana',
    examples:[{word:'のみもの',meaning:'음료 (drink)'},{word:'のり',meaning:'김/풀 (seaweed/glue)'},{word:'のこり',meaning:'나머지 (remainder)'},{word:'のはら',meaning:'들판 (field)'},{word:'のぼる',meaning:'올라가다 (climb)'},{word:'のど',meaning:'목 (throat)'}]},

  // ─── は행 ───
  'は': { romaji:'ha',  korean:'하', english:'hah',   type:'hiragana',
    examples:[{word:'はな',meaning:'꽃/코 (flower/nose)'},{word:'はる',meaning:'봄 (spring)'},{word:'はし',meaning:'젓가락/다리 (chopsticks/bridge)'},{word:'はやい',meaning:'빠르다 (fast)'},{word:'はたらく',meaning:'일하다 (to work)'},{word:'はじめて',meaning:'처음으로 (for the first time)'}]},
  'ひ': { romaji:'hi',  korean:'히', english:'hee',   type:'hiragana',
    examples:[{word:'ひかり',meaning:'빛 (light)'},{word:'ひと',meaning:'사람 (person)'},{word:'ひこうき',meaning:'비행기 (airplane)'},{word:'ひる',meaning:'낮 (noon)'},{word:'ひさしぶり',meaning:'오랜만이에요 (long time no see)'},{word:'ひどい',meaning:'심하다 (terrible)'}]},
  'ふ': { romaji:'fu',  korean:'후', english:'foo',   type:'hiragana',
    examples:[{word:'ふじさん',meaning:'후지산 (Mt. Fuji)'},{word:'ふゆ',meaning:'겨울 (winter)'},{word:'ふね',meaning:'배 (ship)'},{word:'ふくろ',meaning:'봉지/가방 (bag)'},{word:'ふつう',meaning:'보통 (normal)'},{word:'ふとい',meaning:'굵다 (thick)'}]},
  'へ': { romaji:'he',  korean:'헤', english:'heh',   type:'hiragana',
    examples:[{word:'へや',meaning:'방 (room)'},{word:'へいわ',meaning:'평화 (peace)'},{word:'へそ',meaning:'배꼽 (belly button)'},{word:'へた',meaning:'서툴다 (poor at)'},{word:'へん',meaning:'이상하다 (strange)'},{word:'へんじ',meaning:'답장 (reply)'}]},
  'ほ': { romaji:'ho',  korean:'호', english:'hoh',   type:'hiragana',
    examples:[{word:'ほん',meaning:'책 (book)'},{word:'ほし',meaning:'별 (star)'},{word:'ほんとう',meaning:'정말 (really)'},{word:'ほか',meaning:'그 외 (besides)'},{word:'ほそい',meaning:'가늘다 (thin)'},{word:'ほど',meaning:'정도 (degree/extent)'}]},

  // ─── ま행 ───
  'ま': { romaji:'ma',  korean:'마', english:'mah',   type:'hiragana',
    examples:[{word:'まち',meaning:'도시/마을 (town)'},{word:'まど',meaning:'창문 (window)'},{word:'まつり',meaning:'축제 (festival)'},{word:'まいにち',meaning:'매일 (every day)'},{word:'まずい',meaning:'맛없다 (bad taste)'},{word:'まあまあ',meaning:'그럭저럭 (so-so)'}]},
  'み': { romaji:'mi',  korean:'미', english:'mee',   type:'hiragana',
    examples:[{word:'みず',meaning:'물 (water)'},{word:'みどり',meaning:'초록 (green)'},{word:'みち',meaning:'길 (road)'},{word:'みんな',meaning:'모두 (everyone)'},{word:'みせ',meaning:'가게 (shop)'},{word:'みじかい',meaning:'짧다 (short)'}]},
  'む': { romaji:'mu',  korean:'무', english:'moo',   type:'hiragana',
    examples:[{word:'むし',meaning:'벌레 (insect)'},{word:'むすめ',meaning:'딸 (daughter)'},{word:'むら',meaning:'마을 (village)'},{word:'むずかしい',meaning:'어렵다 (difficult)'},{word:'むかし',meaning:'옛날 (long ago)'},{word:'むりょう',meaning:'무료 (free)'}]},
  'め': { romaji:'me',  korean:'메', english:'meh',   type:'hiragana',
    examples:[{word:'めがね',meaning:'안경 (glasses)'},{word:'めだか',meaning:'송사리 (killifish)'},{word:'めずらしい',meaning:'드물다 (rare)'},{word:'めいし',meaning:'명함 (business card)'},{word:'めんどう',meaning:'귀찮다 (troublesome)'},{word:'めった',meaning:'좀처럼 (rarely)'}]},
  'も': { romaji:'mo',  korean:'모', english:'moh',   type:'hiragana',
    examples:[{word:'もり',meaning:'숲 (forest)'},{word:'もの',meaning:'물건 (thing)'},{word:'もち',meaning:'떡 (rice cake)'},{word:'もっと',meaning:'더 (more)'},{word:'もどる',meaning:'돌아가다 (return)'},{word:'もういちど',meaning:'한번 더 (one more time)'}]},

  // ─── や행 ───
  'や': { romaji:'ya',  korean:'야', english:'yah',   type:'hiragana',
    examples:[{word:'やま',meaning:'산 (mountain)'},{word:'やさい',meaning:'채소 (vegetable)'},{word:'やさしい',meaning:'상냥하다 (kind)'},{word:'やすい',meaning:'싸다 (cheap)'},{word:'やきとり',meaning:'야키토리 (grilled chicken)'},{word:'やっと',meaning:'겨우 (finally)'}]},
  'ゆ': { romaji:'yu',  korean:'유', english:'yoo',   type:'hiragana',
    examples:[{word:'ゆき',meaning:'눈 (snow)'},{word:'ゆめ',meaning:'꿈 (dream)'},{word:'ゆびわ',meaning:'반지 (ring)'},{word:'ゆっくり',meaning:'천천히 (slowly)'},{word:'ゆうごはん',meaning:'저녁밥 (dinner)'},{word:'ゆうめい',meaning:'유명하다 (famous)'}]},
  'よ': { romaji:'yo',  korean:'요', english:'yoh',   type:'hiragana',
    examples:[{word:'よる',meaning:'밤 (night)'},{word:'よみかた',meaning:'읽는 법 (how to read)'},{word:'よてい',meaning:'예정 (schedule)'},{word:'よかった',meaning:'다행이다 (that\'s good/relief)'},{word:'ようこそ',meaning:'어서 오세요 (welcome)'},{word:'よっつ',meaning:'넷 (four)'}]},

  // ─── ら행 ───
  'ら': { romaji:'ra',  korean:'라', english:'rah',   type:'hiragana',
    examples:[{word:'らいねん',meaning:'내년 (next year)'},{word:'らく',meaning:'편하다 (comfortable)'},{word:'らっぱ',meaning:'나팔 (trumpet)'},{word:'らいしゅう',meaning:'다음 주 (next week)'},{word:'らーめん',meaning:'라멘 (ramen)'},{word:'らくだ',meaning:'낙타 (camel)'}]},
  'り': { romaji:'ri',  korean:'리', english:'ree',   type:'hiragana',
    examples:[{word:'りんご',meaning:'사과 (apple)'},{word:'りょこう',meaning:'여행 (travel)'},{word:'りょうり',meaning:'요리 (cooking)'},{word:'りか',meaning:'이과 (science)'},{word:'りゆう',meaning:'이유 (reason)'},{word:'りっぱ',meaning:'훌륭하다 (splendid)'}]},
  'る': { romaji:'ru',  korean:'루', english:'roo',   type:'hiragana',
    examples:[{word:'るすばん',meaning:'집 보기 (house-sitting)'},{word:'るいじ',meaning:'유사 (similar)'},{word:'るす',meaning:'부재중 (absent)'},{word:'るーる',meaning:'규칙 (rule)'},{word:'るいけい',meaning:'누계 (cumulative total)'}]},
  'れ': { romaji:'re',  korean:'레', english:'reh',   type:'hiragana',
    examples:[{word:'れんしゅう',meaning:'연습 (practice)'},{word:'れきし',meaning:'역사 (history)'},{word:'れいぞうこ',meaning:'냉장고 (refrigerator)'},{word:'れすとらん',meaning:'레스토랑 (restaurant)'},{word:'れんらく',meaning:'연락 (contact)'},{word:'れい',meaning:'예/예시 (example)'}]},
  'ろ': { romaji:'ro',  korean:'로', english:'roh',   type:'hiragana',
    examples:[{word:'ろうか',meaning:'복도 (hallway)'},{word:'ろく',meaning:'6 (six)'},{word:'ろうそく',meaning:'양초 (candle)'},{word:'ろんぶん',meaning:'논문 (thesis)'},{word:'ろじ',meaning:'골목 (alley)'},{word:'ろっか',meaning:'로커 (locker)'}]},

  // ─── わ·を·ん ───
  'わ': { romaji:'wa',  korean:'와', english:'wah',   type:'hiragana',
    examples:[{word:'わたし',meaning:'나 (I/me)'},{word:'わに',meaning:'악어 (crocodile)'},{word:'わらう',meaning:'웃다 (laugh)'},{word:'わかい',meaning:'젊다 (young)'},{word:'わかる',meaning:'이해하다 (understand)'},{word:'わすれる',meaning:'잊다 (forget)'}]},
  'を': { romaji:'wo',  korean:'오', english:'oh',    type:'hiragana',
    examples:[{word:'〜を食べる',meaning:'~을 먹다 (to eat ~)'},{word:'〜を見る',meaning:'~을 보다 (to see ~)'},{word:'〜を聞く',meaning:'~을 듣다/묻다 (to listen/ask ~)'},{word:'〜を買う',meaning:'~을 사다 (to buy ~)'}]},
  'ん': { romaji:'n',   korean:'음', english:'n/m',   type:'hiragana',
    examples:[{word:'にほん',meaning:'일본 (Japan)'},{word:'てんき',meaning:'날씨 (weather)'},{word:'さんぽ',meaning:'산책 (walk)'},{word:'えんぴつ',meaning:'연필 (pencil)'},{word:'おんがく',meaning:'음악 (music)'},{word:'うんどう',meaning:'운동 (exercise)'}]},

  // ─────────────────── 히라가나 탁음 (濁音) ───────────────────
  'が': { romaji:'ga',  korean:'가', english:'gah',   type:'hiragana_dakuten',
    examples:[{word:'がっこう',meaning:'학교 (school)'},{word:'がいこく',meaning:'외국 (foreign country)'},{word:'がんばる',meaning:'열심히 하다 (do one\'s best)'}]},
  'ぎ': { romaji:'gi',  korean:'기', english:'gee',   type:'hiragana_dakuten',
    examples:[{word:'ぎゅうにゅう',meaning:'우유 (milk)'},{word:'ぎんこう',meaning:'은행 (bank)'},{word:'ぎじゅつ',meaning:'기술 (technology)'}]},
  'ぐ': { romaji:'gu',  korean:'구', english:'goo',   type:'hiragana_dakuten',
    examples:[{word:'ぐち',meaning:'불평 (complaint)'},{word:'ぐんて',meaning:'장갑 (work gloves)'},{word:'ぐたい',meaning:'구체적 (concrete)'}]},
  'げ': { romaji:'ge',  korean:'게', english:'geh',   type:'hiragana_dakuten',
    examples:[{word:'げんき',meaning:'건강함 (healthy)'},{word:'げいじゅつ',meaning:'예술 (art)'},{word:'げた',meaning:'나막신 (wooden clogs)'}]},
  'ご': { romaji:'go',  korean:'고', english:'goh',   type:'hiragana_dakuten',
    examples:[{word:'ごはん',meaning:'밥/식사 (meal/rice)'},{word:'ごご',meaning:'오후 (afternoon)'},{word:'ごちそう',meaning:'잔치 (feast)'}]},

  'ざ': { romaji:'za',  korean:'자', english:'zah',   type:'hiragana_dakuten',
    examples:[{word:'ざっし',meaning:'잡지 (magazine)'},{word:'ざいりょう',meaning:'재료 (ingredient)'},{word:'ざんねん',meaning:'아쉽다 (unfortunate)'}]},
  'じ': { romaji:'ji',  korean:'지', english:'jee',   type:'hiragana_dakuten',
    examples:[{word:'じかん',meaning:'시간 (time)'},{word:'じしん',meaning:'지진 (earthquake)'},{word:'じどうしゃ',meaning:'자동차 (car)'}]},
  'ず': { romaji:'zu',  korean:'즈', english:'zoo',   type:'hiragana_dakuten',
    examples:[{word:'ずっと',meaning:'계속 (all the time)'},{word:'ずかん',meaning:'도감 (illustrated book)'},{word:'ずつう',meaning:'두통 (headache)'}]},
  'ぜ': { romaji:'ze',  korean:'제', english:'zeh',   type:'hiragana_dakuten',
    examples:[{word:'ぜんぶ',meaning:'전부 (all)'},{word:'ぜったい',meaning:'절대 (absolutely)'},{word:'ぜいきん',meaning:'세금 (tax)'}]},
  'ぞ': { romaji:'zo',  korean:'조', english:'zoh',   type:'hiragana_dakuten',
    examples:[{word:'ぞう',meaning:'코끼리 (elephant)'},{word:'ぞうきん',meaning:'걸레 (cleaning rag)'},{word:'ぞんざい',meaning:'무례함 (rudeness)'}]},

  'だ': { romaji:'da',  korean:'다', english:'dah',   type:'hiragana_dakuten',
    examples:[{word:'だいがく',meaning:'대학교 (university)'},{word:'だいじょうぶ',meaning:'괜찮아요 (it\'s okay)'},{word:'だれ',meaning:'누구 (who)'}]},
  'ぢ': { romaji:'ji',  korean:'지', english:'jee',   type:'hiragana_dakuten',
    examples:[{word:'はなぢ',meaning:'코피 (nosebleed)'},{word:'ちぢむ',meaning:'줄어들다 (shrink)'}]},
  'づ': { romaji:'zu',  korean:'즈', english:'zoo',   type:'hiragana_dakuten',
    examples:[{word:'つづく',meaning:'계속되다 (continue)'},{word:'こづかい',meaning:'용돈 (pocket money)'}]},
  'で': { romaji:'de',  korean:'데', english:'deh',   type:'hiragana_dakuten',
    examples:[{word:'でんしゃ',meaning:'전철 (train)'},{word:'でんわ',meaning:'전화 (phone)'},{word:'でんき',meaning:'전기/전등 (electricity/light)'}]},
  'ど': { romaji:'do',  korean:'도', english:'doh',   type:'hiragana_dakuten',
    examples:[{word:'どうぶつ',meaning:'동물 (animal)'},{word:'どうぞ',meaning:'어서요 (please/here you go)'},{word:'どこ',meaning:'어디 (where)'}]},

  'ば': { romaji:'ba',  korean:'바', english:'bah',   type:'hiragana_dakuten',
    examples:[{word:'ばら',meaning:'장미 (rose)'},{word:'ばんごはん',meaning:'저녁밥 (dinner)'},{word:'ばしょ',meaning:'장소 (place)'}]},
  'び': { romaji:'bi',  korean:'비', english:'bee',   type:'hiragana_dakuten',
    examples:[{word:'びっくり',meaning:'깜짝 (surprised)'},{word:'びょうき',meaning:'병 (illness)'},{word:'びじゅつ',meaning:'미술 (fine art)'}]},
  'ぶ': { romaji:'bu',  korean:'부', english:'boo',   type:'hiragana_dakuten',
    examples:[{word:'ぶどう',meaning:'포도 (grapes)'},{word:'ぶた',meaning:'돼지 (pig)'},{word:'ぶんか',meaning:'문화 (culture)'}]},
  'べ': { romaji:'be',  korean:'베', english:'beh',   type:'hiragana_dakuten',
    examples:[{word:'べんきょう',meaning:'공부 (study)'},{word:'べんとう',meaning:'도시락 (lunchbox)'},{word:'べつ',meaning:'별도 (separate)'}]},
  'ぼ': { romaji:'bo',  korean:'보', english:'boh',   type:'hiragana_dakuten',
    examples:[{word:'ぼうし',meaning:'모자 (hat)'},{word:'ぼく',meaning:'나(남성) (I - male)'},{word:'ぼんやり',meaning:'멍하니 (absent-minded)'}]},

  // ─────────────────── 히라가나 반탁음 (半濁音) ───────────────────
  'ぱ': { romaji:'pa',  korean:'파', english:'pah',   type:'hiragana_handakuten',
    examples:[{word:'パン',meaning:'빵 (bread)'},{word:'パパ',meaning:'아빠 (papa)'},{word:'ぱちぱち',meaning:'박수 소리 (clapping sound)'}]},
  'ぴ': { romaji:'pi',  korean:'피', english:'pee',   type:'hiragana_handakuten',
    examples:[{word:'ピアノ',meaning:'피아노 (piano)'},{word:'ぴかぴか',meaning:'반짝반짝 (sparkling)'},{word:'ピンク',meaning:'분홍 (pink)'}]},
  'ぷ': { romaji:'pu',  korean:'푸', english:'poo',   type:'hiragana_handakuten',
    examples:[{word:'プール',meaning:'수영장 (pool)'},{word:'プリン',meaning:'푸딩 (pudding)'},{word:'プレゼント',meaning:'선물 (present)'}]},
  'ぺ': { romaji:'pe',  korean:'페', english:'peh',   type:'hiragana_handakuten',
    examples:[{word:'ペン',meaning:'펜 (pen)'},{word:'ペット',meaning:'반려동물 (pet)'},{word:'ぺらぺら',meaning:'유창하다 (fluent)'}]},
  'ぽ': { romaji:'po',  korean:'포', english:'poh',   type:'hiragana_handakuten',
    examples:[{word:'ポケット',meaning:'주머니 (pocket)'},{word:'ぽかぽか',meaning:'따뜻하다 (warm)'},{word:'ポスト',meaning:'우체통 (mailbox)'}]},

  // ─────────────────── 히라가나 요음 (拗音) ───────────────────
  'きゃ': { romaji:'kya', korean:'캬', english:'kyah', type:'hiragana_yoon',
    examples:[{word:'きゃく',meaning:'손님 (guest)'},{word:'きゃっかん',meaning:'객관 (objective)'}]},
  'きゅ': { romaji:'kyu', korean:'큐', english:'kyoo', type:'hiragana_yoon',
    examples:[{word:'きゅうきゅうしゃ',meaning:'구급차 (ambulance)'},{word:'きゅうり',meaning:'오이 (cucumber)'}]},
  'きょ': { romaji:'kyo', korean:'쿄', english:'kyoh', type:'hiragana_yoon',
    examples:[{word:'きょうと',meaning:'교토 (Kyoto)'},{word:'きょうしつ',meaning:'교실 (classroom)'}]},

  'しゃ': { romaji:'sha', korean:'샤', english:'shah', type:'hiragana_yoon',
    examples:[{word:'しゃしん',meaning:'사진 (photo)'},{word:'しゃかい',meaning:'사회 (society)'}]},
  'しゅ': { romaji:'shu', korean:'슈', english:'shoo', type:'hiragana_yoon',
    examples:[{word:'しゅみ',meaning:'취미 (hobby)'},{word:'しゅくだい',meaning:'숙제 (homework)'}]},
  'しょ': { romaji:'sho', korean:'쇼', english:'shoh', type:'hiragana_yoon',
    examples:[{word:'しょうがっこう',meaning:'초등학교 (elementary school)'},{word:'しょくじ',meaning:'식사 (meal)'}]},

  'ちゃ': { romaji:'cha', korean:'차', english:'chah', type:'hiragana_yoon',
    examples:[{word:'おちゃ',meaning:'녹차 (green tea)'},{word:'ちゃいろ',meaning:'갈색 (brown)'}]},
  'ちゅ': { romaji:'chu', korean:'추', english:'choo', type:'hiragana_yoon',
    examples:[{word:'ちゅうい',meaning:'주의 (attention)'},{word:'ちゅうもん',meaning:'주문 (order)'}]},
  'ちょ': { romaji:'cho', korean:'쵸', english:'choh', type:'hiragana_yoon',
    examples:[{word:'ちょっと',meaning:'잠깐/조금 (a little)'},{word:'ちょうど',meaning:'딱/마침 (just right)'}]},

  'にゃ': { romaji:'nya', korean:'냐', english:'nyah', type:'hiragana_yoon',
    examples:[{word:'にゃんこ',meaning:'고양이(애칭) (kitty)'},{word:'にゃー',meaning:'야옹 (meow)'}]},
  'にゅ': { romaji:'nyu', korean:'뉴', english:'nyoo', type:'hiragana_yoon',
    examples:[{word:'にゅうがく',meaning:'입학 (enrollment)'},{word:'にゅうす',meaning:'뉴스 (news)'}]},
  'にょ': { romaji:'nyo', korean:'뇨', english:'nyoh', type:'hiragana_yoon',
    examples:[{word:'にょきにょき',meaning:'쑥쑥 자라다 (growing rapidly)'}]},

  'ひゃ': { romaji:'hya', korean:'햐', english:'hyah', type:'hiragana_yoon',
    examples:[{word:'ひゃく',meaning:'100 (hundred)'},{word:'ひゃっかてん',meaning:'백화점 (department store)'}]},
  'ひゅ': { romaji:'hyu', korean:'휴', english:'hyoo', type:'hiragana_yoon',
    examples:[{word:'ひゅーひゅー',meaning:'바람 소리 (whistling wind)'}]},
  'ひょ': { romaji:'hyo', korean:'효', english:'hyoh', type:'hiragana_yoon',
    examples:[{word:'ひょう',meaning:'우박/표 (hail/chart)'},{word:'ひょうじ',meaning:'표시 (display)'}]},

  'みゃ': { romaji:'mya', korean:'먀', english:'myah', type:'hiragana_yoon',
    examples:[{word:'みゃく',meaning:'맥박 (pulse)'}]},
  'みゅ': { romaji:'myu', korean:'뮤', english:'myoo', type:'hiragana_yoon',
    examples:[{word:'みゅーじっく',meaning:'뮤직 (music)'}]},
  'みょ': { romaji:'myo', korean:'묘', english:'myoh', type:'hiragana_yoon',
    examples:[{word:'みょうじ',meaning:'성(씨) (last name)'}]},

  'りゃ': { romaji:'rya', korean:'랴', english:'ryah', type:'hiragana_yoon',
    examples:[{word:'りゃくご',meaning:'약어 (abbreviation)'}]},
  'りゅ': { romaji:'ryu', korean:'류', english:'ryoo', type:'hiragana_yoon',
    examples:[{word:'りゅうがく',meaning:'유학 (study abroad)'},{word:'りゅうこう',meaning:'유행 (trend)'}]},
  'りょ': { romaji:'ryo', korean:'료', english:'ryoh', type:'hiragana_yoon',
    examples:[{word:'りょこう',meaning:'여행 (travel)'},{word:'りょうり',meaning:'요리 (cooking)'}]},

  'ぎゃ': { romaji:'gya', korean:'갸', english:'gyah', type:'hiragana_yoon',
    examples:[{word:'ぎゃく',meaning:'반대 (reverse)'},{word:'ぎゃくてん',meaning:'역전 (reversal)'}]},
  'ぎゅ': { romaji:'gyu', korean:'규', english:'gyoo', type:'hiragana_yoon',
    examples:[{word:'ぎゅうにく',meaning:'소고기 (beef)'},{word:'ぎゅうにゅう',meaning:'우유 (milk)'}]},
  'ぎょ': { romaji:'gyo', korean:'교', english:'gyoh', type:'hiragana_yoon',
    examples:[{word:'ぎょうざ',meaning:'만두 (gyoza/dumplings)'},{word:'ぎょうじ',meaning:'행사 (event)'}]},

  'じゃ': { romaji:'ja',  korean:'자', english:'jah',  type:'hiragana_yoon',
    examples:[{word:'じゃがいも',meaning:'감자 (potato)'},{word:'じゃんけん',meaning:'가위바위보 (rock-paper-scissors)'}]},
  'じゅ': { romaji:'ju',  korean:'주', english:'joo',  type:'hiragana_yoon',
    examples:[{word:'じゅうしょ',meaning:'주소 (address)'},{word:'じゅぎょう',meaning:'수업 (class/lesson)'}]},
  'じょ': { romaji:'jo',  korean:'조', english:'joh',  type:'hiragana_yoon',
    examples:[{word:'じょうず',meaning:'잘한다 (skillful)'},{word:'じょせい',meaning:'여성 (female)'}]},

  'びゃ': { romaji:'bya', korean:'뱌', english:'byah', type:'hiragana_yoon',
    examples:[{word:'びゃく',meaning:'밝은 (bright/pure)'}]},
  'びゅ': { romaji:'byu', korean:'뷰', english:'byoo', type:'hiragana_yoon',
    examples:[{word:'びゅーびゅー',meaning:'바람 소리 (whistling sound)'}]},
  'びょ': { romaji:'byo', korean:'뵤', english:'byoh', type:'hiragana_yoon',
    examples:[{word:'びょうき',meaning:'병 (illness)'},{word:'びょういん',meaning:'병원 (hospital)'}]},

  'ぴゃ': { romaji:'pya', korean:'퍄', english:'pyah', type:'hiragana_yoon',
    examples:[{word:'ぴゃーぴゃー',meaning:'꽥꽥 소리 (squealing)'}]},
  'ぴゅ': { romaji:'pyu', korean:'퓨', english:'pyoo', type:'hiragana_yoon',
    examples:[{word:'ぴゅーっと',meaning:'쌩 하고 (swoosh)'}]},
  'ぴょ': { romaji:'pyo', korean:'표', english:'pyoh', type:'hiragana_yoon',
    examples:[{word:'ぴょんぴょん',meaning:'깡충깡충 (hopping)'}]},

  // ─────────────────── 가타가나 기본 ───────────────────
  'ア': { romaji:'a',   korean:'아', english:'ah',    type:'katakana',
    examples:[{word:'アイス',meaning:'아이스크림 (ice cream)'},{word:'アメリカ',meaning:'미국 (America)'},{word:'アニメ',meaning:'애니메이션 (anime)'}]},
  'イ': { romaji:'i',   korean:'이', english:'ee',    type:'katakana',
    examples:[{word:'イタリア',meaning:'이탈리아 (Italy)'},{word:'インターネット',meaning:'인터넷 (internet)'}]},
  'ウ': { romaji:'u',   korean:'우', english:'oo',    type:'katakana',
    examples:[{word:'ウイルス',meaning:'바이러스 (virus)'},{word:'ウクレレ',meaning:'우쿨렐레 (ukulele)'}]},
  'エ': { romaji:'e',   korean:'에', english:'eh',    type:'katakana',
    examples:[{word:'エアコン',meaning:'에어컨 (air conditioner)'},{word:'エレベーター',meaning:'엘리베이터 (elevator)'}]},
  'オ': { romaji:'o',   korean:'오', english:'oh',    type:'katakana',
    examples:[{word:'オレンジ',meaning:'오렌지 (orange)'},{word:'オーストラリア',meaning:'호주 (Australia)'}]},

  'カ': { romaji:'ka',  korean:'카', english:'kah',   type:'katakana',
    examples:[{word:'カメラ',meaning:'카메라 (camera)'},{word:'カフェ',meaning:'카페 (cafe)'},{word:'カレー',meaning:'카레 (curry)'}]},
  'キ': { romaji:'ki',  korean:'키', english:'key',   type:'katakana',
    examples:[{word:'キッチン',meaning:'부엌 (kitchen)'},{word:'キャンプ',meaning:'캠핑 (camping)'}]},
  'ク': { romaji:'ku',  korean:'쿠', english:'koo',   type:'katakana',
    examples:[{word:'クラス',meaning:'클래스 (class)'},{word:'クリスマス',meaning:'크리스마스 (Christmas)'}]},
  'ケ': { romaji:'ke',  korean:'케', english:'keh',   type:'katakana',
    examples:[{word:'ケーキ',meaning:'케이크 (cake)'},{word:'ケータイ',meaning:'휴대폰 (mobile phone)'}]},
  'コ': { romaji:'ko',  korean:'코', english:'koh',   type:'katakana',
    examples:[{word:'コーヒー',meaning:'커피 (coffee)'},{word:'コンビニ',meaning:'편의점 (convenience store)'}]},

  'サ': { romaji:'sa',  korean:'사', english:'sah',   type:'katakana',
    examples:[{word:'サラダ',meaning:'샐러드 (salad)'},{word:'サッカー',meaning:'축구 (soccer)'}]},
  'シ': { romaji:'shi', korean:'시', english:'shee',  type:'katakana',
    examples:[{word:'シャツ',meaning:'셔츠 (shirt)'},{word:'システム',meaning:'시스템 (system)'}]},
  'ス': { romaji:'su',  korean:'스', english:'soo',   type:'katakana',
    examples:[{word:'スポーツ',meaning:'스포츠 (sports)'},{word:'スマホ',meaning:'스마트폰 (smartphone)'}]},
  'セ': { romaji:'se',  korean:'세', english:'seh',   type:'katakana',
    examples:[{word:'セーター',meaning:'스웨터 (sweater)'},{word:'センター',meaning:'센터 (center)'}]},
  'ソ': { romaji:'so',  korean:'소', english:'soh',   type:'katakana',
    examples:[{word:'ソファ',meaning:'소파 (sofa)'},{word:'ソフトウェア',meaning:'소프트웨어 (software)'}]},

  'タ': { romaji:'ta',  korean:'타', english:'tah',   type:'katakana',
    examples:[{word:'タクシー',meaning:'택시 (taxi)'},{word:'テーブル',meaning:'테이블 (table)'}]},
  'チ': { romaji:'chi', korean:'치', english:'chee',  type:'katakana',
    examples:[{word:'チーズ',meaning:'치즈 (cheese)'},{word:'チケット',meaning:'티켓 (ticket)'}]},
  'ツ': { romaji:'tsu', korean:'츠', english:'tsoo',  type:'katakana',
    examples:[{word:'ツアー',meaning:'투어 (tour)'},{word:'ツイッター',meaning:'트위터 (Twitter)'}]},
  'テ': { romaji:'te',  korean:'테', english:'teh',   type:'katakana',
    examples:[{word:'テレビ',meaning:'TV (television)'},{word:'テスト',meaning:'시험 (test)'}]},
  'ト': { romaji:'to',  korean:'토', english:'toh',   type:'katakana',
    examples:[{word:'トマト',meaning:'토마토 (tomato)'},{word:'トイレ',meaning:'화장실 (toilet)'}]},

  'ナ': { romaji:'na',  korean:'나', english:'nah',   type:'katakana',
    examples:[{word:'ナイフ',meaning:'나이프 (knife)'},{word:'ナンバー',meaning:'번호 (number)'}]},
  'ニ': { romaji:'ni',  korean:'니', english:'nee',   type:'katakana',
    examples:[{word:'ニュース',meaning:'뉴스 (news)'},{word:'ニコニコ',meaning:'니코니코 (smiling)'}]},
  'ヌ': { romaji:'nu',  korean:'누', english:'noo',   type:'katakana',
    examples:[{word:'ヌードル',meaning:'누들 (noodle)'},{word:'ヌード',meaning:'누드 (nude)'}]},
  'ネ': { romaji:'ne',  korean:'네', english:'neh',   type:'katakana',
    examples:[{word:'ネット',meaning:'인터넷/망 (net)'},{word:'ネクタイ',meaning:'넥타이 (necktie)'}]},
  'ノ': { romaji:'no',  korean:'노', english:'noh',   type:'katakana',
    examples:[{word:'ノート',meaning:'노트 (notebook)'},{word:'ノック',meaning:'노크 (knock)'}]},

  'ハ': { romaji:'ha',  korean:'하', english:'hah',   type:'katakana',
    examples:[{word:'ハンバーガー',meaning:'햄버거 (hamburger)'},{word:'ハワイ',meaning:'하와이 (Hawaii)'}]},
  'ヒ': { romaji:'hi',  korean:'히', english:'hee',   type:'katakana',
    examples:[{word:'ヒーロー',meaning:'히어로 (hero)'},{word:'ヒント',meaning:'힌트 (hint)'}]},
  'フ': { romaji:'fu',  korean:'후', english:'foo',   type:'katakana',
    examples:[{word:'フランス',meaning:'프랑스 (France)'},{word:'フルーツ',meaning:'과일 (fruit)'}]},
  'ヘ': { romaji:'he',  korean:'헤', english:'heh',   type:'katakana',
    examples:[{word:'ヘルメット',meaning:'헬멧 (helmet)'},{word:'ヘッドフォン',meaning:'헤드폰 (headphones)'}]},
  'ホ': { romaji:'ho',  korean:'호', english:'hoh',   type:'katakana',
    examples:[{word:'ホテル',meaning:'호텔 (hotel)'},{word:'ホームページ',meaning:'홈페이지 (homepage)'}]},

  'マ': { romaji:'ma',  korean:'마', english:'mah',   type:'katakana',
    examples:[{word:'マクドナルド',meaning:'맥도날드 (McDonald\'s)'},{word:'マスク',meaning:'마스크 (mask)'}]},
  'ミ': { romaji:'mi',  korean:'미', english:'mee',   type:'katakana',
    examples:[{word:'ミルク',meaning:'우유 (milk)'},{word:'ミュージック',meaning:'음악 (music)'}]},
  'ム': { romaji:'mu',  korean:'무', english:'moo',   type:'katakana',
    examples:[{word:'ムード',meaning:'무드 (mood)'},{word:'ムービー',meaning:'영화 (movie)'}]},
  'メ': { romaji:'me',  korean:'메', english:'meh',   type:'katakana',
    examples:[{word:'メール',meaning:'이메일 (email)'},{word:'メニュー',meaning:'메뉴 (menu)'}]},
  'モ': { romaji:'mo',  korean:'모', english:'moh',   type:'katakana',
    examples:[{word:'モデル',meaning:'모델 (model)'},{word:'モバイル',meaning:'모바일 (mobile)'}]},

  'ヤ': { romaji:'ya',  korean:'야', english:'yah',   type:'katakana',
    examples:[{word:'ヤフー',meaning:'야후 (Yahoo)'},{word:'ヤード',meaning:'야드 (yard)'}]},
  'ユ': { romaji:'yu',  korean:'유', english:'yoo',   type:'katakana',
    examples:[{word:'ユーチューブ',meaning:'유튜브 (YouTube)'},{word:'ユニフォーム',meaning:'유니폼 (uniform)'}]},
  'ヨ': { romaji:'yo',  korean:'요', english:'yoh',   type:'katakana',
    examples:[{word:'ヨーグルト',meaning:'요거트 (yogurt)'},{word:'ヨーロッパ',meaning:'유럽 (Europe)'}]},

  'ラ': { romaji:'ra',  korean:'라', english:'rah',   type:'katakana',
    examples:[{word:'ラーメン',meaning:'라면 (ramen)'},{word:'ラジオ',meaning:'라디오 (radio)'}]},
  'リ': { romaji:'ri',  korean:'리', english:'ree',   type:'katakana',
    examples:[{word:'リモコン',meaning:'리모컨 (remote control)'},{word:'リズム',meaning:'리듬 (rhythm)'}]},
  'ル': { romaji:'ru',  korean:'루', english:'roo',   type:'katakana',
    examples:[{word:'ルール',meaning:'규칙 (rule)'},{word:'ルーム',meaning:'룸 (room)'}]},
  'レ': { romaji:'re',  korean:'레', english:'reh',   type:'katakana',
    examples:[{word:'レストラン',meaning:'레스토랑 (restaurant)'},{word:'レポート',meaning:'리포트 (report)'}]},
  'ロ': { romaji:'ro',  korean:'로', english:'roh',   type:'katakana',
    examples:[{word:'ロボット',meaning:'로봇 (robot)'},{word:'ロシア',meaning:'러시아 (Russia)'}]},

  'ワ': { romaji:'wa',  korean:'와', english:'wah',   type:'katakana',
    examples:[{word:'ワイン',meaning:'와인 (wine)'},{word:'ワールド',meaning:'월드 (world)'}]},
  'ヲ': { romaji:'wo',  korean:'오', english:'oh',    type:'katakana',
    examples:[{word:'(조사로만 사용)',meaning:'particle (object marker)'}]},
  'ン': { romaji:'n',   korean:'음', english:'n/ng',  type:'katakana',
    examples:[{word:'テレビン',meaning:'테레빈 (turpentine)'},{word:'ランチ',meaning:'점심 (lunch)'}]},

  // ─────────────────── 가타가나 탁음 (濁音) ───────────────────
  'ガ': { romaji:'ga',  korean:'가', english:'gah',   type:'katakana_dakuten',
    examples:[{word:'ガム',meaning:'껌 (gum)'},{word:'ガレージ',meaning:'차고 (garage)'}]},
  'ギ': { romaji:'gi',  korean:'기', english:'gee',   type:'katakana_dakuten',
    examples:[{word:'ギター',meaning:'기타 (guitar)'},{word:'ギリシャ',meaning:'그리스 (Greece)'}]},
  'グ': { romaji:'gu',  korean:'구', english:'goo',   type:'katakana_dakuten',
    examples:[{word:'グラス',meaning:'글라스/잔 (glass)'},{word:'グーグル',meaning:'구글 (Google)'}]},
  'ゲ': { romaji:'ge',  korean:'게', english:'geh',   type:'katakana_dakuten',
    examples:[{word:'ゲーム',meaning:'게임 (game)'},{word:'ゲスト',meaning:'게스트 (guest)'}]},
  'ゴ': { romaji:'go',  korean:'고', english:'goh',   type:'katakana_dakuten',
    examples:[{word:'ゴルフ',meaning:'골프 (golf)'},{word:'ゴール',meaning:'골 (goal)'}]},

  'ザ': { romaji:'za',  korean:'자', english:'zah',   type:'katakana_dakuten',
    examples:[{word:'ザッピング',meaning:'채널 돌리기 (zapping)'},{word:'ザンビア',meaning:'잠비아 (Zambia)'}]},
  'ジ': { romaji:'ji',  korean:'지', english:'jee',   type:'katakana_dakuten',
    examples:[{word:'ジュース',meaning:'주스 (juice)'},{word:'ジャケット',meaning:'재킷 (jacket)'}]},
  'ズ': { romaji:'zu',  korean:'즈', english:'zoo',   type:'katakana_dakuten',
    examples:[{word:'ズボン',meaning:'바지 (pants)'},{word:'ズーム',meaning:'줌 (zoom)'}]},
  'ゼ': { romaji:'ze',  korean:'제', english:'zeh',   type:'katakana_dakuten',
    examples:[{word:'ゼリー',meaning:'젤리 (jelly)'},{word:'ゼロ',meaning:'제로/0 (zero)'}]},
  'ゾ': { romaji:'zo',  korean:'조', english:'zoh',   type:'katakana_dakuten',
    examples:[{word:'ゾーン',meaning:'존/구역 (zone)'},{word:'ゾンビ',meaning:'좀비 (zombie)'}]},

  'ダ': { romaji:'da',  korean:'다', english:'dah',   type:'katakana_dakuten',
    examples:[{word:'ダンス',meaning:'댄스 (dance)'},{word:'ダイヤ',meaning:'다이아 (diamond)'}]},
  'ヂ': { romaji:'ji',  korean:'지', english:'jee',   type:'katakana_dakuten',
    examples:[{word:'(드물게 사용)',meaning:'rarely used, same sound as ジ'}]},
  'ヅ': { romaji:'zu',  korean:'즈', english:'zoo',   type:'katakana_dakuten',
    examples:[{word:'(드물게 사용)',meaning:'rarely used, same sound as ズ'}]},
  'デ': { romaji:'de',  korean:'데', english:'deh',   type:'katakana_dakuten',
    examples:[{word:'デザイン',meaning:'디자인 (design)'},{word:'デート',meaning:'데이트 (date)'}]},
  'ド': { romaji:'do',  korean:'도', english:'doh',   type:'katakana_dakuten',
    examples:[{word:'ドア',meaning:'문 (door)'},{word:'ドラマ',meaning:'드라마 (drama)'}]},

  'バ': { romaji:'ba',  korean:'바', english:'bah',   type:'katakana_dakuten',
    examples:[{word:'バス',meaning:'버스 (bus)'},{word:'バナナ',meaning:'바나나 (banana)'}]},
  'ビ': { romaji:'bi',  korean:'비', english:'bee',   type:'katakana_dakuten',
    examples:[{word:'ビール',meaning:'맥주 (beer)'},{word:'ビデオ',meaning:'비디오 (video)'}]},
  'ブ': { romaji:'bu',  korean:'부', english:'boo',   type:'katakana_dakuten',
    examples:[{word:'ブログ',meaning:'블로그 (blog)'},{word:'ブランド',meaning:'브랜드 (brand)'}]},
  'ベ': { romaji:'be',  korean:'베', english:'beh',   type:'katakana_dakuten',
    examples:[{word:'ベッド',meaning:'침대 (bed)'},{word:'ベルト',meaning:'벨트 (belt)'}]},
  'ボ': { romaji:'bo',  korean:'보', english:'boh',   type:'katakana_dakuten',
    examples:[{word:'ボール',meaning:'공 (ball)'},{word:'ボタン',meaning:'버튼 (button)'}]},

  // ─────────────────── 가타가나 반탁음 (半濁音) ───────────────────
  'パ': { romaji:'pa',  korean:'파', english:'pah',   type:'katakana_handakuten',
    examples:[{word:'パスポート',meaning:'여권 (passport)'},{word:'パーティー',meaning:'파티 (party)'}]},
  'ピ': { romaji:'pi',  korean:'피', english:'pee',   type:'katakana_handakuten',
    examples:[{word:'ピザ',meaning:'피자 (pizza)'},{word:'ピアノ',meaning:'피아노 (piano)'}]},
  'プ': { romaji:'pu',  korean:'푸', english:'poo',   type:'katakana_handakuten',
    examples:[{word:'プール',meaning:'수영장 (pool)'},{word:'プリンター',meaning:'프린터 (printer)'}]},
  'ペ': { romaji:'pe',  korean:'페', english:'peh',   type:'katakana_handakuten',
    examples:[{word:'ペット',meaning:'반려동물 (pet)'},{word:'ペン',meaning:'펜 (pen)'}]},
  'ポ': { romaji:'po',  korean:'포', english:'poh',   type:'katakana_handakuten',
    examples:[{word:'ポケモン',meaning:'포켓몬 (Pokémon)'},{word:'ポスター',meaning:'포스터 (poster)'}]},

  // ─────────────────── 가타가나 요음 ───────────────────
  'キャ': { romaji:'kya', korean:'캬', english:'kyah', type:'katakana_yoon',
    examples:[{word:'キャラクター',meaning:'캐릭터 (character)'},{word:'キャンセル',meaning:'취소 (cancel)'}]},
  'キュ': { romaji:'kyu', korean:'큐', english:'kyoo', type:'katakana_yoon',
    examples:[{word:'キュート',meaning:'귀엽다 (cute)'},{word:'キュービック',meaning:'큐빅 (cubic)'}]},
  'キョ': { romaji:'kyo', korean:'쿄', english:'kyoh', type:'katakana_yoon',
    examples:[{word:'キョウト(京都)',meaning:'교토 (Kyoto)'}]},

  'シャ': { romaji:'sha', korean:'샤', english:'shah', type:'katakana_yoon',
    examples:[{word:'シャワー',meaning:'샤워 (shower)'},{word:'シャンプー',meaning:'샴푸 (shampoo)'}]},
  'シュ': { romaji:'shu', korean:'슈', english:'shoo', type:'katakana_yoon',
    examples:[{word:'シュークリーム',meaning:'슈크림 (cream puff)'},{word:'シュート',meaning:'슛 (shoot)'}]},
  'ショ': { romaji:'sho', korean:'쇼', english:'shoh', type:'katakana_yoon',
    examples:[{word:'ショッピング',meaning:'쇼핑 (shopping)'},{word:'ショー',meaning:'쇼 (show)'}]},

  'チャ': { romaji:'cha', korean:'차', english:'chah', type:'katakana_yoon',
    examples:[{word:'チャンス',meaning:'찬스/기회 (chance)'},{word:'チャンネル',meaning:'채널 (channel)'}]},
  'チュ': { romaji:'chu', korean:'추', english:'choo', type:'katakana_yoon',
    examples:[{word:'チューリップ',meaning:'튤립 (tulip)'},{word:'チューブ',meaning:'튜브 (tube)'}]},
  'チョ': { romaji:'cho', korean:'쵸', english:'choh', type:'katakana_yoon',
    examples:[{word:'チョコレート',meaning:'초콜릿 (chocolate)'},{word:'チョコ',meaning:'초코 (choco)'}]},

  'ニャ': { romaji:'nya', korean:'냐', english:'nyah', type:'katakana_yoon',
    examples:[{word:'ニャンコ',meaning:'고양이(애칭) (kitty)'}]},
  'ニュ': { romaji:'nyu', korean:'뉴', english:'nyoo', type:'katakana_yoon',
    examples:[{word:'ニュース',meaning:'뉴스 (news)'},{word:'ニューヨーク',meaning:'뉴욕 (New York)'}]},
  'ニョ': { romaji:'nyo', korean:'뇨', english:'nyoh', type:'katakana_yoon',
    examples:[{word:'ニョッキ',meaning:'뇨키 (gnocchi)'}]},

  'ヒャ': { romaji:'hya', korean:'햐', english:'hyah', type:'katakana_yoon',
    examples:[{word:'ヒャク',meaning:'100 (hundred)'}]},
  'ヒュ': { romaji:'hyu', korean:'휴', english:'hyoo', type:'katakana_yoon',
    examples:[{word:'ヒューズ',meaning:'퓨즈 (fuse)'},{word:'ヒューストン',meaning:'휴스턴 (Houston)'}]},
  'ヒョ': { romaji:'hyo', korean:'효', english:'hyoh', type:'katakana_yoon',
    examples:[{word:'ヒョウ',meaning:'표범 (leopard)'}]},

  'ミャ': { romaji:'mya', korean:'먀', english:'myah', type:'katakana_yoon',
    examples:[{word:'ミャンマー',meaning:'미얀마 (Myanmar)'}]},
  'ミュ': { romaji:'myu', korean:'뮤', english:'myoo', type:'katakana_yoon',
    examples:[{word:'ミュージック',meaning:'뮤직 (music)'},{word:'ミュージアム',meaning:'뮤지엄 (museum)'}]},
  'ミョ': { romaji:'myo', korean:'묘', english:'myoh', type:'katakana_yoon',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},

  'リャ': { romaji:'rya', korean:'랴', english:'ryah', type:'katakana_yoon',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},
  'リュ': { romaji:'ryu', korean:'류', english:'ryoo', type:'katakana_yoon',
    examples:[{word:'リュック',meaning:'배낭 (backpack)'},{word:'リュクサック',meaning:'배낭 (rucksack)'}]},
  'リョ': { romaji:'ryo', korean:'료', english:'ryoh', type:'katakana_yoon',
    examples:[{word:'リョーマ',meaning:'료마 (proper name)'}]},

  'ギャ': { romaji:'gya', korean:'갸', english:'gyah', type:'katakana_yoon',
    examples:[{word:'ギャップ',meaning:'갭/차이 (gap)'},{word:'ギャラリー',meaning:'갤러리 (gallery)'}]},
  'ギュ': { romaji:'gyu', korean:'규', english:'gyoo', type:'katakana_yoon',
    examples:[{word:'ギュっと',meaning:'꽉 (tightly)'}]},
  'ギョ': { romaji:'gyo', korean:'교', english:'gyoh', type:'katakana_yoon',
    examples:[{word:'ギョーザ',meaning:'만두 (gyoza)'}]},

  'ジャ': { romaji:'ja',  korean:'자', english:'jah',  type:'katakana_yoon',
    examples:[{word:'ジャム',meaning:'잼 (jam)'},{word:'ジャズ',meaning:'재즈 (jazz)'}]},
  'ジュ': { romaji:'ju',  korean:'주', english:'joo',  type:'katakana_yoon',
    examples:[{word:'ジュース',meaning:'주스 (juice)'},{word:'ジュエリー',meaning:'주얼리 (jewelry)'}]},
  'ジョ': { romaji:'jo',  korean:'조', english:'joh',  type:'katakana_yoon',
    examples:[{word:'ジョグ',meaning:'조깅 (jog)'},{word:'ジョーク',meaning:'농담 (joke)'}]},

  'ビャ': { romaji:'bya', korean:'뱌', english:'byah', type:'katakana_yoon',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},
  'ビュ': { romaji:'byu', korean:'뷰', english:'byoo', type:'katakana_yoon',
    examples:[{word:'ビュッフェ',meaning:'뷔페 (buffet)'},{word:'ビュー',meaning:'뷰/전망 (view)'}]},
  'ビョ': { romaji:'byo', korean:'뵤', english:'byoh', type:'katakana_yoon',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},

  'ピャ': { romaji:'pya', korean:'퍄', english:'pyah', type:'katakana_yoon',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},
  'ピュ': { romaji:'pyu', korean:'퓨', english:'pyoo', type:'katakana_yoon',
    examples:[{word:'ピュア',meaning:'순수 (pure)'},{word:'コンピュータ',meaning:'컴퓨터 (computer)'}]},
  'ピョ': { romaji:'pyo', korean:'표', english:'pyoh', type:'katakana_yoon',
    examples:[{word:'(드물게 사용)',meaning:'rarely used in katakana'}]},

  // ─────────────────── 특수 박자 (Special Mora) ───────────────────
  'っ': { romaji:'(tt/kk/ss)', korean:'촉음', english:'dbl.cons.', type:'special',
    examples:[{word:'きって',meaning:'우표 (stamp)'},{word:'ざっし',meaning:'잡지 (magazine)'},{word:'ちょっと',meaning:'잠깐 (just a moment)'},{word:'きっぷ',meaning:'표 (ticket)'},{word:'がっこう',meaning:'학교 (school)'},{word:'もっと',meaning:'더 (more)'}]},
  'ッ': { romaji:'(TT/KK/SS)', korean:'촉음(가타)', english:'dbl.cons.', type:'special',
    examples:[{word:'コップ',meaning:'컵 (cup)'},{word:'ベッド',meaning:'침대 (bed)'},{word:'ネット',meaning:'인터넷 (net)'},{word:'バッグ',meaning:'가방 (bag)'},{word:'チケット',meaning:'티켓 (ticket)'},{word:'ショッピング',meaning:'쇼핑 (shopping)'}]},
  'ー': { romaji:'ā/ī/ū/ē/ō', korean:'장음부', english:'long vowel', type:'special',
    examples:[{word:'コーヒー',meaning:'커피 (coffee)'},{word:'スーパー',meaning:'슈퍼마켓 (supermarket)'},{word:'ケーキ',meaning:'케이크 (cake)'},{word:'ラーメン',meaning:'라멘 (ramen)'},{word:'バター',meaning:'버터 (butter)'},{word:'ビール',meaning:'맥주 (beer)'}]},
  'おう': { romaji:'ō (오~)', korean:'お+う 장음', english:'long O', type:'special',
    examples:[{word:'おとうさん',meaning:'아버지 (father)'},{word:'おうさま',meaning:'임금님 (king)'},{word:'とうきょう',meaning:'도쿄 (Tokyo)'},{word:'こうえん',meaning:'공원 (park)'},{word:'どうぞ',meaning:'어서요 (please)'},{word:'もうすぐ',meaning:'곧 (soon)'}]},
  'えい': { romaji:'ē (에~)', korean:'え+い 장음', english:'long E', type:'special',
    examples:[{word:'えいご',meaning:'영어 (English)'},{word:'えいが',meaning:'영화 (movie)'},{word:'せんせい',meaning:'선생님 (teacher)'},{word:'けいたい',meaning:'휴대폰 (mobile phone)'},{word:'えいきゅう',meaning:'영원 (eternity)'},{word:'めいし',meaning:'명함 (business card)'}]},
  'ああ': { romaji:'ā (아~)', korean:'あ+あ 장음', english:'long A', type:'special',
    examples:[{word:'おかあさん',meaning:'어머니 (mother)'},{word:'おばあさん',meaning:'할머니 (grandmother)'},{word:'おばあちゃん',meaning:'할머니 (grandma, familiar)'},{word:'さあ',meaning:'자~ (now then / come on)'}]},
  'いい': { romaji:'ī (이~)', korean:'い+い 장음', english:'long I', type:'special',
    examples:[{word:'おにいさん',meaning:'오빠/형 (older brother)'},{word:'おじいさん',meaning:'할아버지 (grandfather)'},{word:'いい',meaning:'좋다 (good/fine)'},{word:'ちいさい',meaning:'작다 (small)'}]},
  'うう': { romaji:'ū (우~)', korean:'う+う 장음', english:'long U', type:'special',
    examples:[{word:'ふうせん',meaning:'풍선 (balloon)'},{word:'くうき',meaning:'공기 (air)'},{word:'すうじ',meaning:'숫자 (number)'},{word:'じゆう',meaning:'자유 (freedom)'},{word:'ゆうめい',meaning:'유명하다 (famous)'},{word:'つうきん',meaning:'통근 (commute)'}]},

  // ─────────────────── 가타가나 외래어 확장 (Extended Katakana) ───────────────────
  'ファ': { romaji:'fa', korean:'파', english:'fah', type:'katakana_extended',
    examples:[{word:'ファッション',meaning:'패션 (fashion)'},{word:'ソファ',meaning:'소파 (sofa)'},{word:'ファイル',meaning:'파일 (file)'},{word:'ファン',meaning:'팬 (fan)'}]},
  'フィ': { romaji:'fi', korean:'피', english:'fee', type:'katakana_extended',
    examples:[{word:'フィルム',meaning:'필름 (film)'},{word:'フィナーレ',meaning:'피날레 (finale)'},{word:'フィットネス',meaning:'피트니스 (fitness)'},{word:'フィンランド',meaning:'핀란드 (Finland)'}]},
  'フェ': { romaji:'fe', korean:'페', english:'feh', type:'katakana_extended',
    examples:[{word:'カフェ',meaning:'카페 (cafe)'},{word:'フェリー',meaning:'페리 (ferry)'},{word:'フェスティバル',meaning:'페스티벌 (festival)'},{word:'フェイク',meaning:'가짜 (fake)'}]},
  'フォ': { romaji:'fo', korean:'포', english:'foh', type:'katakana_extended',
    examples:[{word:'フォーク',meaning:'포크 (fork)'},{word:'フォーム',meaning:'폼/양식 (form)'},{word:'フォルダ',meaning:'폴더 (folder)'},{word:'フォロー',meaning:'팔로우 (follow)'}]},
  'ティ': { romaji:'ti', korean:'티', english:'tee', type:'katakana_extended',
    examples:[{word:'ティッシュ',meaning:'티슈 (tissue)'},{word:'パーティー',meaning:'파티 (party)'},{word:'ティアラ',meaning:'티아라 (tiara)'},{word:'ティーム',meaning:'팀 (team)'}]},
  'ディ': { romaji:'di', korean:'디', english:'dee', type:'katakana_extended',
    examples:[{word:'ディスコ',meaning:'디스코 (disco)'},{word:'ディズニー',meaning:'디즈니 (Disney)'},{word:'ディナー',meaning:'디너 (dinner)'},{word:'メディア',meaning:'미디어 (media)'}]},
  'トゥ': { romaji:'tu', korean:'투', english:'too', type:'katakana_extended',
    examples:[{word:'トゥデイ',meaning:'오늘 (today)'},{word:'トゥルー',meaning:'진실 (true)'},{word:'トゥーン',meaning:'툰/만화 (toon)'}]},
  'ドゥ': { romaji:'du', korean:'두', english:'doo', type:'katakana_extended',
    examples:[{word:'ドゥ',meaning:'두 (do - 드물게 사용 / rarely used)'},{word:'ドゥオ',meaning:'듀오 (duo)'}]},
  'ウィ': { romaji:'wi', korean:'위', english:'wee', type:'katakana_extended',
    examples:[{word:'ウィンドウ',meaning:'창문/윈도우 (window)'},{word:'ウィキ',meaning:'위키 (wiki)'},{word:'ウィスキー',meaning:'위스키 (whisky)'},{word:'ウィルス',meaning:'바이러스 (virus)'}]},
  'ウェ': { romaji:'we', korean:'웨', english:'weh', type:'katakana_extended',
    examples:[{word:'ウェブ',meaning:'웹 (web)'},{word:'ウェイター',meaning:'웨이터 (waiter)'},{word:'ウェルカム',meaning:'웰컴 (welcome)'},{word:'スウェーデン',meaning:'스웨덴 (Sweden)'}]},
  'ウォ': { romaji:'wo', korean:'워', english:'woh', type:'katakana_extended',
    examples:[{word:'ウォーター',meaning:'물 (water)'},{word:'ウォーク',meaning:'워크 (walk)'},{word:'ウォーミング',meaning:'워밍업 (warming up)'},{word:'ウォレット',meaning:'지갑 (wallet)'}]},
  'チェ': { romaji:'che', korean:'체', english:'cheh', type:'katakana_extended',
    examples:[{word:'チェック',meaning:'체크 (check)'},{word:'チェリー',meaning:'체리 (cherry)'},{word:'チェンジ',meaning:'체인지 (change)'},{word:'チェーン',meaning:'체인 (chain)'}]},
  'シェ': { romaji:'she', korean:'셰', english:'sheh', type:'katakana_extended',
    examples:[{word:'シェア',meaning:'공유 (share)'},{word:'シェフ',meaning:'셰프 (chef)'},{word:'シェルター',meaning:'대피소 (shelter)'},{word:'シェイク',meaning:'쉐이크 (shake)'}]},
  'ジェ': { romaji:'je', korean:'제', english:'jeh', type:'katakana_extended',
    examples:[{word:'ジェット',meaning:'제트 (jet)'},{word:'ジェリー',meaning:'젤리 (jelly)'},{word:'ジェスチャー',meaning:'제스처 (gesture)'},{word:'ジェネレーション',meaning:'세대 (generation)'}]},
  'ヴ': { romaji:'vu', korean:'뷔', english:'voo', type:'katakana_extended',
    examples:[{word:'ヴァイオリン',meaning:'바이올린 (violin)'},{word:'ヴェネチア',meaning:'베네치아 (Venice)'}]},
  'ヴァ': { romaji:'va', korean:'바(v)', english:'vah', type:'katakana_extended',
    examples:[{word:'ヴァイオリン',meaning:'바이올린 (violin)'},{word:'ヴァカンス',meaning:'바캉스 (vacation)'},{word:'ヴァレンタイン',meaning:'발렌타인 (Valentine)'}]},
  'ヴィ': { romaji:'vi', korean:'비(v)', english:'vee', type:'katakana_extended',
    examples:[{word:'ヴィラ',meaning:'빌라 (villa)'},{word:'ヴィジョン',meaning:'비전 (vision)'},{word:'ヴィーナス',meaning:'비너스 (Venus)'}]},
  'ヴェ': { romaji:'ve', korean:'베(v)', english:'veh', type:'katakana_extended',
    examples:[{word:'ヴェネチア',meaning:'베네치아 (Venice)'},{word:'ヴェール',meaning:'베일 (veil)'},{word:'ヴェテラン',meaning:'베테랑 (veteran)'}]},
  'ヴォ': { romaji:'vo', korean:'보(v)', english:'voh', type:'katakana_extended',
    examples:[{word:'ヴォーカル',meaning:'보컬 (vocal)'},{word:'ヴォリューム',meaning:'볼륨 (volume)'}]},
  'イェ': { romaji:'ye', korean:'예', english:'yeh', type:'katakana_extended',
    examples:[{word:'イェルサレム',meaning:'예루살렘 (Jerusalem)'},{word:'イェス',meaning:'예스 (yes - 고어)'}]},

  // ─────────────────── 조사 읽기 예외 (Particle Reading Exceptions) ───────────────────
  'は_p': { kana:'は', romaji:'wa', korean:'와 (주제조사)', english:'wa (topic)', type:'particle',
    examples:[{word:'わたし は',meaning:'나는 (I [topic])'},{word:'これ は',meaning:'이것은 (this is...)'},{word:'きょう は',meaning:'오늘은 (today...)'},{word:'あなた は',meaning:'당신은 (you [topic])'}]},
  'へ_p': { kana:'へ', romaji:'e', korean:'에 (방향조사)', english:'e (direction)', type:'particle',
    examples:[{word:'がっこう へ',meaning:'학교로 (to school)'},{word:'にほん へ',meaning:'일본으로 (to Japan)'},{word:'うち へ',meaning:'집으로 (to home)'},{word:'どこ へ',meaning:'어디로 (to where)'}]},
  'を_p': { kana:'を', romaji:'o', korean:'을/를 (목적조사)', english:'o (object)', type:'particle',
    examples:[{word:'みず を',meaning:'물을 (water [object])'},{word:'りんご を',meaning:'사과를 (apple [object])'},{word:'にほんご を',meaning:'일본어를 (Japanese [object])'},{word:'おんがく を',meaning:'음악을 (music [object])'}]}
};

// 모든 가나를 타입별로 그룹화
function getCharsByType(type) {
  return Object.keys(KANA_MAP).filter(k => KANA_MAP[k].type === type);
}

// 레벨의 캐릭터 데이터 반환
function getLevelChars(levelId) {
  const level = LEVELS.find(l => l.id === levelId);
  if (!level) return [];
  return level.chars.map(k => ({ kana: k, ...KANA_MAP[k] })).filter(c => c.romaji);
}

// 퀴즈용 오답 선택지 생성 (같은 타입에서 랜덤)
function getWrongOptions(correctKana, count = 3, fieldType = 'romaji') {
  const info = KANA_MAP[correctKana];
  if (!info) return [];
  const sameType = Object.entries(KANA_MAP)
    .filter(([k, v]) => k !== correctKana && v.type === info.type && v[fieldType] !== info[fieldType]);
  const shuffled = sameType.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map(([k, v]) => ({kana: k, ...v}));
}

if (typeof module !== 'undefined') {
  module.exports = { LEVELS, KANA_MAP, getLevelChars, getWrongOptions, getCharsByType };
}
